= Definizione della macrotipologia didattica

La macrotipologia didattica, ovverosia la struttura complessiva del progetto, è
caratterizzata dalla scelta della tipologia di e-learning, dall'analisi
dell'utenza, del contenuto, dell'obiettivo e dell'infrastruttura. Quindi, si
analizzano i vincoli di ingresso e le loro relazioni per la produzione del
presente documento di lavoro.

== Analisi dei vincoli di ingresso e delle relazioni

=== Analisi dell'utenza

Il corso di chitarra di livello base è rivolto a tutti coloro che sono interessati 
a imparare a suonare la chitarra. Per quanto riguarda le competenze, l'utente dovrebbe
conoscere alcuni concetti base della teoria della musica ma non è strettamente necessario
in quanto verranno effettuati alcuni richiami agli aspetti teorici più importanti. Essendo 
di livello base, il corso risulterebbe inutile ad utenti che hanno già una buona affinità 
con la chitarra. Per quanto riguarda l'età, l'utente deve avere almeno 13 anni, in quanto 
si ritiene che l'insegnamento della chitarra ai bambini debba essere meno rigoroso e più
basato sul "`diverire per apprendere`". Sono stati presi in esame diversi aspetti
(discussi nelle sezioni seguenti) per comprendere quali sono le caratteristiche dei 
potenziali utenti.

==== Distanza fisica

Gli utenti possono anche non essere in italia ma si presuppone che abbiano
una buona padronanza della lingua italiana. Proprio per questi motivi, non c'è
nessuna possibilità di una lezione fisica in sede. Il corso sarà interamente organizzato
in modo tale da non far risultare necessaria la presenza fisica di un insegnante, permettendo a
chiunque di avere accesso al materiale didattico in qualsiasi momento. La mancanza di incontri 
in presenza potrà essere sostituita da incontri online.

==== Numero

Il corso non avrà un numero massimo di utenti. Ovviamente, il materiale didattico 
deve essere fruibile a tutti gli utenti iscritti.
La gestione di incontri online con un elevato numero di studenti, però, risulterebbe
molto complicato e impossibile, quindi, solo in caso di incontri online, verranno
organizzati dei gruppi di lavoro per effettuare le lezioni online.

==== Accesso dell'utente alla tecnologia

L'utente dovrà solo avere la conoscenza di accedere ad un browser internet, 
aspetto che ormai tutti conoscono in quest'epoca.
Non sono necessarie altre competenze informatiche e non è prevista nessuna
configurazione di alcun tipo.

==== Expertise di dominio dell'utente

Come detto in precedenza, si consiglia che l'utente abbia la conoscenza di teoria
musicale di base ma non è strettamente necessario.
L'utente può anche non conoscere alcun tipo di nozione del dominio.
Questo aspetto però non mette alcun limite alla sua possibilità di aumentare la sua
conoscenza del dominio e di imparare a suonare la chitarra. 

==== Omogeneità o disomogeneità di interesse tra i partecipanti

L'obbietivo del corso è noto a tutti, gli studenti che parteciperanno sono
studenti che hanno scelto liberamente di iscriversi.
In base alla loro voglia di imparare, ognuno raggiungerà un livello diverso.
Questo interesse o questa voglia può anche non essere omogenea tra tutti 
i partecipanti.
Gli studenti che perdono il piacere di imparare a suonare la chitarra potranno
liberamente abbandonare il corso.

==== Disponibilità del partecipante alla condivisione e alla collaborazione

La musica inevitabilmente favorisce la relazione tra studenti.
L'arte della musica porterà ad invogliare i partecipanti alla collaborazione
con gli altri iscritti, sia per chiarire eventuali dubbi e migliorarsi e sia
per suonare e divertirsi insieme.
La comunicazione può avvenire tramite gli strumenti disposti dalla piattaforma 
(forum, chat, ecc.) o anche tramite social network.
Da non dimenticare però il mezzo di comunicazione più importante, "`la musica`".

== Analisi dell'obiettivo

Gli obiettivi formativi sono definiti utilizzando la _tassonomia di Bloom_ al
fine di categorizzare gli obiettivi educativi nel dominio conoscitivo, che
riguarda le attività intellettuali e logiche. Tale dominio viene suddiviso nei
seguenti obiettivi didattici, ordinati di seguito dal più semplice al più
complesso: _Conoscenza_, _Comprensione_, _Analisi_, _Applicazione_, _Sintesi_ e
_Valutazione_.

Il corso si pone l'obiettivo di raggiungere il livello di Applicazione. Nelle
seguenti sezioni si riportano gli obiettivi e le motivazioni dei tre livelli
coperti dal corso.

Conoscenza:: L'utente deve essere in grado di rievocare il materiale memorizzato
e richiamare alla memoria fatti, metodi e processi. Per verificare la
correttezza della conoscenza acquisita dallo studente, al termine delle attività
didattiche, saranno inseriti dei brevi test di autovalutazione (nelle forme di
domande a risposta multipla e/o test vero/falso).

Comprensione:: L'utente deve essere in grado di afferrare il senso delle
informazioni e di saperle trasformare. Pertanto, per favorire l'acquisizione e
l'estrapolazione delle informazioni saranno inserite durante le lezioni delle
immagini, degli esempi e/o dei grafici che accompagnino la spiegazione. Ogni
studente deve quindi essere in grado di rispondere a domande poste in maniera
differente rispetto a quanto riportato all'interno del materiale didattico.

Applicazione:: L'utente deve essere in grado di utilizzare il materiale
conosciuto per risolvere problemi nuovi e deve inoltre saper utilizzare
rappresentazioni astratte in casi concreti. Nel caso specifico dello strumento
musicale, lo studente deve essere in grado di utilizzare in pratica ciò che ha
studiato dal materiale didattico astratto e deve inoltre essere in grado di
utilizzare le tecniche apprese in nuovi contesti (per esempio, imparando
autonomamente a suonare una composizione nuova). Ai fini della valutazione di
questo aspetto, al termine del corso lo studente dovrà affrontare un esame in
cui non solo gli verranno poste delle domande nuove legate al materiale
didattico, ma dovrà partecipare a una conferenza con il docente per valutare la
sua capacità di suonare effettivamente lo strumento con composizione nuove.

Si sottolinea che non tutte le lezioni (elencate nella sezione
"`<<sect-unità>>`") potrebbero avere la necessità di coprire tutti i tre
livelli: in alcuni casi può essere sufficiente fermarsi a un livello inferiore.
I casi specifici per ogni lezione sono riportati nella <<tab-lezioni-bloom>>.

[#tab-lezioni-bloom]
[options="header", cols="^.^10h,^.^15,^.^25a,^.^20,^.^20a", stripes=even]
.Attività, obiettivi e livelli della tassonomia di Bloom per ogni unità
|===
| N.ro Unità | Titolo unità | Attività | Obiettivo | Tassonomia di Bloom

| 1
| Introduzione allo strumento
| * Conoscenza delle componenti principali dello strumento e dei suoi principi
  fondamentali
| Lo studente deve conoscere quali sono le componenti fondamentali dello
  strumento che sta utilizzando e deve conoscere quali sono le "`regole`" e i
  principi basilari della disciplina
| * Conoscenza

| 2
| Utilizzare il pianoforte
| * Comprendere come posizionarsi per suonare lo strumento e come rendere
  indipendenti le dita. 
  * Comprendere come una diteggiatura corretta può migliorare la qualità
  dell'attività
| Lo studente deve essere in grado di comprendere quali sono le posizioni
  corrette da assumere allo strumento, in modo da poterne sviluppare delle
  proprie in modo cosciente. Inoltre, deve essere in grado di comprendere la
  simbologia utilizzata per indicare la diteggiatura.
| * Conoscenza
  * Comprensione

| 3
| Leggere uno spartito
| * Comprensione della simbologia basilare della partitura musicale.
  * Comprensione delle differenze fra la notazione italiana e quella
  internazionale.
| Lo studente deve essere in grado di leggere una partitura musicale di base.
  Deve essere inoltre in grado di trasporre le informazioni lette in notazione
  internazionale.
| * Conoscenza
  * Comprensione
  * Applicazione

| 4
| Suonare il pianoforte
| * Individuazione delle note nel pianoforte.
  * Utilizzo degli accordi e dei rivolti, in modo basilare.
  * Applicazione della teoria in un caso di studio.
| Lo studente deve essere in grado di applicare tutto quel che ha studiato
  durante il corso per suonare un semplice pezzo senza la necessità di un
  accompagnamento del docente.
| * Conoscenza
  * Comprensione
  * Applicazione

|===

== Analisi del contenuto

[#sect-lezioni]
=== Suddivisione del corso in lezioni

* Unità 1: Introduzione allo strumento
  ** Lezione 1.1: Le componenti dello strumento
  ** Lezione 1.2: I principi fondamentali del pianoforte
* Unità 2: Utilizzare il pianoforte
  ** Lezione 2.1: La posizione della mano
  ** Lezione 2.2: L'indipendenza delle dita
  ** Lezione 2.3: La diteggiatura
* Unità 3: Leggere uno spartito
  ** Lezione 3.1: Le basi della partitura musicale
  ** Lezione 3.2: La notazione internazionale
* Unità 4: Suonare il pianoforte
  ** Lezione 4.1: Le note sul pianoforte
  ** Lezione 4.2: Gli accordi
  ** Lezione 4.3: Semplificare gli accordi: i rivolti
  ** Lezione 4.4: Applicare in pratica: "`No Woman No Cry`"
  

== Analisi dell'infrastruttura
