= Definizione della macrotipologia didattica

La macrotipologia didattica, ovverosia la struttura complessiva del progetto, è
caratterizzata dalla scelta della tipologia di e-learning, dall'analisi
dell'utenza, del contenuto, dell'obiettivo e dell'infrastruttura. Quindi, si
analizzano i vincoli di ingresso e le loro relazioni per la produzione del
presente documento di lavoro.

== Analisi dei vincoli di ingresso e delle relazioni

=== Analisi dell'utenza

L'utenza a cui è destinata la piattaforma è ampia e variegata. Tuttavia si
presuppone una età minima di circa tredici anni, in quanto si ritiene che
l'insegnamento della musica ai bambini debba essere meno rigoroso e basato sul
"`divertirsi per apprendere`". Di seguito si riportano i vincoli dell'utenza dei
vari corsi, mantenendo però validi i vincoli generali appena presentati.

==== Corso di teoria musicale di livello base

L'utenza a cui è destinato il corso di teoria base è ampia e variegata. Questo
principalmente poichè il corso non richiede di averne seguiti altri, essendo
esso il corso propedeutico a tutti gli altri. Per tal motivo non vi sono delle
limitazioni legate all'età, sia bambini che adulti possono fruire del corso
senza problemi.

==== Corso di teoria musicale di livello avanzato

L'utenza a cui si rivolge il corso di teoria avanzata è ampia (in età) ma
richiede una conoscenza musicale di base che è fondamentale per la corretta
comprensione dei contenuti che il corso propone. Il corso in sè può fungere da
"`trampolino di lancio`" per permettere all'utente di imparare uno o più
strumenti avendo, al contempo, una base solida. Sono stati presi in esame
diversi aspetti (discussi nelle sezioni seguenti) per comprendere quali sono le
caratteristiche dei potenziali utenti.

==== Corso di batteria di livello base

Gli utenti a cui è rivolto il corso di batteria di livello base possono avere
età e competenze differenti, l'importante è che siano interessati a imparare a
suonare questo strumento . Sono stati presi in esame diversi aspetti (che sono
stati discussi nelle sezioni seguenti) per comprendere quali sono le
caratteristiche dei potenziali utenti.

==== Corso di chitarra di livello base

Il corso di chitarra di livello base è rivolto a tutti coloro che sono
interessati a imparare a suonare la chitarra. Per quanto riguarda le competenze,
l'utente dovrebbe conoscere alcuni concetti base della teoria della musica.
Essendo di livello base, il corso risulterebbe inutile ad utenti che hanno già
una buona affinità con la chitarra. Sono stati presi in esame diversi aspetti
(discussi nelle sezioni seguenti) per comprendere quali sono le caratteristiche
dei potenziali utenti.

==== Corso di pianoforte di livello base

L'utenza a cui è rivolta la piattaforma è ampia (sia in età che in competenze) e
include tutti coloro interessati a conoscere il mondo della musica e a imparare
a suonare uno strumento. Sono stati presi in esame diversi aspetti (discussi
nelle sezioni seguenti) per comprendere quali sono le caratteristiche dei
potenziali utenti.

==== Distanza fisica

Gli utenti possono potenzialmente essere sparsi in tutto il globo, ma si
presuppone una buona padronanza della lingua italiana. Inoltre, sia per
problematiche legate alla disponibilità temporale degli utenti, per la loro
potenziale locazione geografica e ma anche per i problemi legati alla pandemia
che si sta vivendo, non è possibile presupporre la possibilità di partecipare
fisicamente in sede alle attività. Per questo motivo l'utente, accedendo alla
piattaforma, deve poter usufruire del materiale didattico in qualsiasi momento.
Inoltre, il fattore della distanza fisica agisce direttamente sugli incontri in
presenza organizzabili, che (qualora necessari) devono essere necessariamente
sostituiti da incontri online.

==== Numero

Il numero degli utenti non è prevedibile a priori. Per questo motivo il
materiale didattico deve essere fruibile senza limiti di utenti attivi
contemporaneamente. Una eccezione riguarda gli incontri online organizzati:
qualora il numero di iscritti al corso fosse ingestibile per una singola
conferenza, è possibile suddividere il gruppo in gruppi di lavoro con cui
organizzare singolarmente degli incontri (per esempio, nel caso in cui ci sia
bisogno di effettuare un workshop con tutti gli allievi in un unico incontro).

Nel caso in cui, invece, fosse necessario l'incontro online per perfezionare
determinate tecniche e/o la postura dell'allievo (quindi un ricevimento per
ulteriori chiarimenti) sarà necessario avere una video lezione online con il
singolo studente in quanto si potrebbe creare confusione tra i partecipanti
(specialmente nel caso specifico di alcuni strumenti musicali, come la
batteria).

==== Accesso dell'utente alla tecnologia

Le competenze e conoscenze informatiche degli utenti sono varie, ma tutti
conoscono almeno come si utilizza un browser internet. Non sono necessarie
configurazioni di alcun tipo, quindi gli utenti non è richiesto alcuna
competenza specifica. L'unico prerequisito "`tecnologico`" del corso è l'accesso
a uno strumento su cui far pratica (qualora si seguisse un corso pratico).

==== Expertise di dominio dell'utente

===== Corso di teoria musicale di livello base

Si presume che i partecipanti del corso (almeno per una buona parte) non abbiano
mai avuto alcun contatto con il mondo della musica. Per questo motivo, deve
essere fornito un vocabolario di base minimo che permetta la comunicazione.

===== Corso di teoria musicale di livello avanzato

Si presume che i partecipanti del corso abbiano già una base di teoria della
musica conoscendo già le terminologie di base, lo spartito, le note i valori e
le pause.

===== Corso di pianoforte, chitarra e batteria di livello base

Si presume che i partecipanti del corso (almeno per una buona parte) non abbiano
mai avuto alcun contatto con il mondo della musica. Per questo motivo, deve
essere fornito un vocabolario di base minimo che permetta la comunicazione, ma
tale vocabolario non deve e non può sostituire un corso di teoria musicale di
base, che resta un prerequisito consigliato del corso.

// NOTE: Inserire dei glossari sui termini non inerenti alla teoria ma utili?
//  esempio: "membranofono" per la tipologia di strumento

==== Omogeneità o disomogeneità di interesse tra i partecipanti

L'interesse medio sarà omogeneo in quanto tutti i partecipanti scelgono
liberamente di iscriversi al corso in base alle proprie preferenze e alle
proprie inclinazioni. Inoltre, al superamento di una prova finale, sarà
consegnato ai partecipanti un attestato di partecipazione e superamento del
corso: questo terrà vivo l'interesse dei partecipanti.

Gli interessi medi potrebbero, tuttavia, non essere omogenei fra tutti i
partecipanti nel lungo termine. Per questo motivo, gli studenti che perdono il
piacere di imparare le nozioni trattate sono liberi di abbandonare il corso.

==== Disponibilità del partecipante alla condivisione e alla collaborazione

La musica inevitabilmente favorisce la relazione tra studenti. Per questo motivo
il partecipante, nel suo interesse, sarà invogliato alla collaborazione con
altri iscritti per approfondire argomenti, chiarire dubbi, risolvere problemi e
confrontarsi. Tali comunicazioni possono avvenire mediante gli strumenti
disposti dalla piattaforma (forum, chat, ecc.) ma anche con modalità esterne
(social network, software di _Instant Messaging_, ecc.). Da non dimenticare però
il mezzo di comunicazione più importante, "`la musica`".

== Analisi dell'obiettivo

Gli obiettivi formativi sono definiti utilizzando la _tassonomia di Bloom_ al
fine di categorizzare gli obiettivi educativi nel dominio conoscitivo, che
riguarda le attività intellettuali e logiche. Tale dominio viene suddiviso nei
seguenti obiettivi didattici, ordinati di seguito dal più semplice al più
complesso: _Conoscenza_, _Comprensione_,  _Applicazione_, _Analisi_, _Sintesi_ e
_Valutazione_.

Il corso si pone l'obiettivo di raggiungere il livello di Applicazione. Nelle
seguenti sezioni si riportano gli obiettivi e le motivazioni dei tre livelli
coperti dal corso.

Conoscenza:: L'utente deve essere in grado di rievocare il materiale memorizzato
e richiamare alla memoria fatti, metodi e processi. Per verificare la
correttezza della conoscenza acquisita dallo studente, al termine delle attività
didattiche, saranno inseriti dei brevi test di autovalutazione (nelle forme di
domande a risposta multipla e/o test vero/falso).

Comprensione:: L'utente deve essere in grado di afferrare il senso delle
informazioni e di saperle trasformare. Pertanto, per favorire l'acquisizione e
l'estrapolazione delle informazioni saranno inserite durante le lezioni delle
immagini, degli esempi e/o dei grafici che accompagnino la spiegazione. Ogni
studente deve quindi essere in grado di rispondere a domande poste in maniera
differente rispetto a quanto riportato all'interno del materiale didattico.

Applicazione:: L'utente deve essere in grado di utilizzare il materiale
conosciuto per risolvere problemi nuovi e deve inoltre saper utilizzare
rappresentazioni astratte in casi concreti. Nel caso specifico dello strumento
musicale, lo studente deve essere in grado di utilizzare in pratica ciò che ha
studiato dal materiale didattico astratto e deve inoltre essere in grado di
utilizzare le tecniche apprese in nuovi contesti (per esempio, imparando
autonomamente a suonare una composizione nuova). Ai fini della valutazione di
questo aspetto, al termine del corso lo studente dovrà affrontare un esame in
cui non solo gli verranno poste delle domande nuove legate al materiale
didattico, ma dovrà partecipare a una conferenza con il docente per valutare la
sua capacità di suonare effettivamente lo strumento con composizione nuove.

Si sottolinea che non tutte le lezioni (elencate nella sezione
"`<<sect-lezioni>>`") potrebbero avere la necessità di
coprire tutti i tre livelli: in alcuni casi può essere sufficiente fermarsi a un
livello inferiore. I casi specifici per ogni lezione sono riportati nella
<<sec-lezioni-bloom>>.

[#sec-lezioni-bloom]
=== Attività, obiettivi e livelli della tassonomia di Bloom

[#tab-lezioni-bloom-teoria-base]
[options="header", cols="^.^10h,^.^15,^.^25a,^.^20,^.^20a", stripes=even]
.Attività, obiettivi e livelli della tassonomia di Bloom per ogni modulo del corso di teoria di livello base
|===
| N.ro Modulo | Titolo modulo | Attività | Obiettivo | Tassonomia di Bloom

| 1
| Fondamenti della musica
| * Autoapprendimento da ipertesti
| Lo studente deve conoscere quali sono gli elementi fondamentali alla base
  della musica, comprenderli e saperli utilizzare nel loro insieme.
  *Valutazione:* test a risposta multipla.
| * Conoscenza

| 2
| Elementi di uno spartito
| * Autoapprendimento da ipertesti
| Lo studente deve essere in grado di comprendere quali sono gli elementi alla
  base di uno spartito, che funzioni svolgono e come vengono messi insieme.
  *Valutazione:* test a risposta multipla con domande formulate in modo diverso
  rispetto al testo.
| * Conoscenza
  * Comprensione

| 3
| Introduzione al tempo
| * Autoapprendimento da ipertesti
| Lo studente deve essere in grado di definire il termine _ritmo_ e spiegare i
  metodi di rappresentazione del _tempo_. *Valutazione:* test a risposta
  multipla con domande formulate in modo diverso; la valutazione dell'obiettivo
  di applicazione è rimandato all'esame finale.
| * Conoscenza
  * Comprensione
  * Applicazione

|===

[#tab-lezioni-bloom-teoria-avanzata]
[options="header", cols="^.^10h,^.^15,^.^25a,^.^20,^.^20a", stripes=even]
.Attività, obiettivi e livelli della tassonomia di Bloom per ogni modulo del corso di teoria di livello avanzato
|===
| N.ro Modulo | Titolo modulo | Attività | Obiettivo | Tassonomia di Bloom

| 1
| Tono, semitono e alterazioni
| * Apprendimento da ipertesti
| Lo studente deve essere in grado di comprendere le principali differenze tra
  toni e semitoni e deve saper comprendere e giustificare le scelte delle
  alterazioni all'interno dello spartito. *Valutazione:* test vero/falso con
  domande formulate in modo diverso rispetto al testo.
| * Conoscenza
  * Comprensione

| 2
| Scala diatonica, gli intervalli e il cromatismo
| * Apprendimento da ipertesti
| Lo studente deve comprendere l'importanza delle scale diatoniche e conoscere 
  gli intervalli congiunti, disgiunti e melodici. Inoltre, deve comprendere le
  differenze tra toni, semitoni diatonici e semitoni cromatici. *Valutazione:*
  test vero/falso con domande formulate in modo diverso rispetto al testo.
| * Conoscenza
  * Comprensione

| 3
| La tonalità, il modo e l'accordo tonale
| * Apprendimento da ipertesti
| Lo studente deve conoscere le tonalità delle varie note e il loro grado,
  i due possibili modi delle tonalità ovvero maggiore e minore, comprendere
  l'accordo tonale e la nota differenziale e personale. *Valutazione:* test
  vero/falso con domande formulate in modo diverso rispetto al testo.
| * Conoscenza
  * Comprensione
|===

[#tab-lezioni-bloom-batteria-base]
[options="header", cols="^.^10h,^.^15,^.^25a,^.^20,^.^20a", stripes=even]
.Attività, obiettivi e livelli della tassonomia di Bloom per ogni modulo del corso di batteria di livello base
|===
| N.ro Modulo | Titolo modulo | Attività | Obiettivo | Tassonomia di Bloom

| 1
| Introduzione allo strumento
| * Autoapprendimento da ipertesti
| Lo studente deve conoscere quali sono le componenti fondamentali dello
  strumento che sta utilizzando e deve conoscere quali sono le "`regole`" e i
  principi basilari della disciplina. *Valutazione:* test vero/falso a fine lezione teorica, test propedeutico a risposta multipla
  con domande formulate in modo diverso rispetto al testo (presente a fine modulo) e consegna di una
  foto/video dimostrativo sull'impugnatura delle bacchette.
| * Conoscenza
  * Comprensione
  * Applicazione

| 2
| Rudimenti
| * Autoapprendimento da ipertesti
  * Videolezioni preregistrate
  * Video di esempio
| Lo studente deve essere in grado di comprendere cosa sono i rudimenti, quali
  sono quelli di base e deve essere in grado di applicare i rudimenti suonandoli
  su una batteria (o su un pad, o su una qualsiasi percussione). *Valutazione:* test vero/falso a fine lezione teorica,
  test propedeutico a risposta multipla con domande formulate in modo diverso rispetto al
  testo (presente a fine modulo) e consegna di uno o più video registrati per valutare la pratica.
| * Conoscenza
  * Comprensione
  * Applicazione

| 3
| Accenti
| * Autoapprendimento da ipertesti
  * Videolezioni preregistrate
  * Video di esempio
| Lo studente deve essere in grado comprendere cosa sono gli accenti e quali
  sono quelli fondamentali. Deve essere inoltre in grado di riprodurre gli
  accenti studiati su una batteria (o su un pad, o su una qualsiasi
  percussione). *Valutazione:* test vero/falso a fine lezione teorica, test propedeutico a risposta multipla con domande formulate in
  modo diverso rispetto al testo (presente a fine modulo) e consegna di uno o più video registrati per valutare
  la pratica.
| * Conoscenza
  * Comprensione
  * Applicazione
|===

[#tab-lezioni-bloom-chitarra-base]
[options="header", cols="^.^10h,^.^15,^.^25a,^.^20,^.^20a", stripes=even]
.Attività, obiettivi e livelli della tassonomia di Bloom per ogni modulo del corso di chitarra di livello base
|===
| N.ro Modulo | Titolo modulo | Attività | Obiettivo | Tassonomia di Bloom

| 1
| Introduzione e utilizzo della chitarra
| * Autoapprendimento da ipertesti
| Lo studente deve conoscere quali sono le componenti fondamentali dello
  strumento che sta utilizzando e deve conoscere quali sono le "`regole`" e i
  principi basilari della disciplina Lo studente deve rafforzare i muscoli delle
  dita e della mano per essere in grado di utilizzare al meglio lo strumento e
  per suonare, in futuro, correttamente gli accordi. *Valutazione:* test a
  risposta multipla con domande formulate in modo diverso rispetto al testo.
| * Conoscenza
  * Comprensione

| 2
| Apprendimento degli accordi principali
| * Autoapprendimento mediante schema dell'accordo, foto e audio di validazione
| Lo studente deve essere in grado di ricordare a memoria e correttamente eseguire
  tutti i 24 accordi principali di base. *Valutazione:* test a risposta multipla
  con domande formulate in modo diverso rispetto al testo e consegne multiple di
  video registrati per valutare la pratica.
| * Conoscenza
  * Comprensione
  * Applicazione

| 3
| Suonare la chitarra
| * Autoapprendimento da ipertesti
| Lo studente deve essere in grado di effettuare correttamente gli accordi che dovrebbe
  ricordare a memoria e deve essere in grado di cambiarli il più velocemente
  possibile per l'esecuzione di una canzone Lo studente deve anche imparare a
  rendere indipendenti le due mani e deve riuscire a comprendere il ritmo di una
  canzone e successivamente replicarla. *Valutazione:* test a risposta multipla
  con domande formulate in modo diverso rispetto al testo. La valutazione
  dell'obiettivo di applicazione è posticipato all'esame finale.
| * Conoscenza
  * Comprensione
  * Applicazione

|===

[#tab-lezioni-bloom-piano-base]
[options="header", cols="^.^10h,^.^15,^.^25a,^.^20,^.^20a", stripes=even]
.Attività, obiettivi e livelli della tassonomia di Bloom per ogni modulo del corso di pianoforte di livello base
|===
| N.ro Modulo | Titolo Modulo | Attività | Obiettivo | Tassonomia di Bloom

| 1
| Introduzione allo strumento
| * Autoapprendimento da ipertesti
| Lo studente deve conoscere quali sono le componenti fondamentali dello
  strumento che sta utilizzando e deve conoscere quali sono le "`regole`" e i
  principi basilari della disciplina. *Valutazione:* test a risposta multipla.
| * Conoscenza

| 2
| Apprendimento degli accordi principali
| * Autoapprendimento da ipertesti
  * Autoapprendimento mediante schemi, video e audio
| Lo studente deve essere in grado di ricordare correttamente ed eseguire
  tutti i 24 accordi principali di base. *Valutazione:* test a risposta multipla
  con domande formulate in modo diverso rispetto al testo e consegne multiple di
  foto per valutare la pratica.
| * Conoscenza
  * Comprensione
  * Applicazione

| 3
| Suonare il pianoforte
| * Autoapprendimento da ipertesti
  * Autoapprendimento mediante schemi
  * Videolezioni preregistrate
| Lo studente deve essere in grado di applicare tutto quel che ha studiato
  durante il corso per suonare un semplice pezzo senza la necessità di un
  accompagnamento del docente.*Valutazione:* test a risposta multipla con
  domande formulate in modo diverso rispetto al testo; la valutazione
  dell'obiettivo di applicazione è rimandata all'esame finale.
| * Conoscenza
  * Comprensione
  * Applicazione

|===

== Analisi del contenuto

I contenuti del corso sono analizzati in base alle seguenti caratteristiche:

Apertura o chiusura:: Il contenuto è principalmente (ma non totalmente) chiuso,
in quanto trattasi di fatti e concetti. Tuttavia vi sono alcune eccezioni in cui
i contenuti risultano aperti in quanto principi o processi. Nel caso specifico
del corso di teoria di livello avanzato, il contenuto è totalmente chiuso in
quanto trattasi di fatti e concetti

Stabilità o instabilità:: I contenuti delle lezioni sono stabili, in quanto il
corso tratta di argomenti ben radicati nell'ambito musicale. È possibile
prevedere aggiornamenti futuri, dovuti all'avanzamento della materia, ma è poco
probabile che tali aggiornamenti riguardino le tecniche e i principi di base
trattati in questo corso.

Testualità, multimedialità e interattività:: Le lezioni si presentano nella
forma di ipertesti multimediali comprensivi, quindi, di testo, immagini, video
e/o animazioni. L'interattività è espressa mediante l'uso di hyperlink (tipici
negli ipertesti) e dei test complessivi. Saranno presenti test al termine di
tutti i moduli didattici, utili ai fini di un'autovalutazione, e dei test
complessivi che servono a valutare lo studente per considerare il corso completo
e superato.

[#sect-lezioni]
=== Suddivisione del corso in lezioni

Corso di teoria musicale di livello base::
  * Modulo 1: Fondamenti della musica
    ** Lezione 1.1: Il suono
    ** Lezione 1.2: Le note
  * Modulo 2: Elementi di uno spartito
    ** Lezione 2.1: Il rigo
    ** Lezione 2.2: Le chiavi
    ** Lezione 2.3: I valori e le pause
  * Modulo 3: Introduzione al tempo
    ** Lezione 3.1: Il ritmo
    ** Lezione 3.2: Il tempo
  * Esame finale
+
[options="header", cols="^.^20h, ^.^40, ^.^40a"]
.I contenuti del corso di teoria musicale di livello base
|===
| Tipo di contenuto | Descrizione | Esempi

| Fatti (chiuso)
| Un insieme di dati dal carattere specifico e unico
| * Il suono
* Le note
* Il rigo
* Il tempo

| Concetti (chiuso/aperto)
| Categoria che include al suo interno molteplici esemplificazioni
| * Le chiavi
* I valori e le pause
* Il ritmo

| Principi (aperto)
| Indicazioni generali e linee guida
|

|===

Corso di teoria musicale di livello avanzato::
  * Unità 1: Tono, semitono e alterazioni
    ** Lezione 1.1: Il tono e il semitono
    ** Lezione 1.2: Le alterazioni
  * Unità 2: Scala diatonica, gli intervalli e il cromatismo
    ** Lezione 2.1: La scala diatonica
    ** Lezione 2.2: Gli intervalli
    ** Lezione 2.3: Il tono e il semitono diatonico e cromatico
  * Unità 3: La tonalità, il modo e l'accordo tonale
    ** Lezione 4.1: La tonalità e il modo
    ** Lezione 4.2: L'accordo tonale
  * Esame finale
+
[options="header", cols="^.^20h, ^.^40, ^.^40a"]
.I contenuti del corso di teoria musicale di livello avanzato
|===
| Tipo di contenuto | Descrizione | Esempi

| Fatti (chiuso)
| Un insieme di dati dal carattere specifico e unico
| * Il tono e il semitono
  * Le alterazioni
  * La scala diatonica
  * La tonalità e il modo

|===

Corso di batteria di livello base::
  * Modulo 1: Introduzione allo strumento
    ** Lezione 1.1: Struttura dello strumento
    ** Lezione 1.2: I concetti fondamentali della batteria
    ** Lezione 1.3: Impugnatura della bacchetta
  * Modulo 2: Rudimenti 
    ** Lezione 2.1: Introduzione ai rudimenti
    ** Lezione 2.2: Rudimenti di base
    ** Lezione 2.3: Propedeuticità dei rudimenti
  * Modulo 3: Accenti 
    ** Lezione 3.1: Introduzione agli accenti
    ** Lezione 3.2: Rudimenti con gli accenti
  * Esame finale
+
[options="header", cols="^.^20h, ^.^40, ^.^40a"]
.I contenuti del corso di batteria di livello base
|===
| Tipo di contenuto | Descrizione | Esempi

| Fatti (chiuso)
| Un insieme di dati dal carattere specifico e unico
| * Struttura dello strumento
  * Introduzione ai rudimenti
  * Introduzione agli accenti
| Concetti (chiuso/aperto)
| Categoria che include al suo interno molteplici esemplificazioni
| * L'impugnatura della bacchetta
  * Rudimenti di base
  * Propedeuticità dei rudimenti
  * Rudimenti con gli accenti
| Principi (aperto)
| Indicazioni generali e linee guida
| * I concetti fondamentali della batteria
|===

Corso di chitarra di livello base::
  * Modulo 1: Introduzione e utilizzo della chitarra
    ** Lezione 1.1: Le componenti dello strumento
    ** Lezione 1.2: Accordatura e corretto utilizzo delle dita
    ** Lezione 1.3: Conoscenza delle note
    ** Lezione 1.4: L'indipendenza delle dita e il barrè
  * Modulo 2: Apprendimento degli accordi principali
    ** Lezione 2.1: Accordi maggiori
    ** Lezione 2.2: Accordi minori
    ** Lezione 2.3: Accordi diesis maggiori
    ** Lezione 2.4: Accordi diesis minori
  * Modulo 3: Suonare la chitarra
    ** Lezione 3.1: Giri armonici
    ** Lezione 3.2: Introduzione del ritmo e del metronomo
    ** Lezione 3.3: Utilizzo della mano destra
    ** Lezione 3.4: Applicare in pratica: "`Albachiara`"
  * Esame finale
+
[options="header", cols="^.^20h, ^.^40, ^.^40a"]
.I contenuti del corso di chitarra di livello base
|===
| Tipo di contenuto | Descrizione | Esempi

| Fatti (chiuso)
| Un insieme di dati dal carattere specifico e unico
| * I componenti dello strumento
  * Accordatura e corretto utilizzo delle dita
  * Conoscenza delle note
  * Accordi maggiori
  * Accordi minori
  * Accordi diesis maggiori
  * Accordi diesis minori
  * Giri armonici

| Concetti (chiuso/aperto)
| Categoria che include al suo interno molteplici esemplificazioni
| * La posizione della mano
  * L'indipendenza delle dita e il barrè
  * Introduzione del ritmo e del metronomo
  * Utilizzo della mano destra

| Principi (aperto)
| Indicazioni generali e linee guida
| 

|===

Corso di pianoforte di livello base::
  * Modulo 1: Introduzione allo strumento
    ** Lezione 1.1: Le componenti dello strumento
    ** Lezione 1.2: I principi fondamentali del pianoforte
    ** Lezione 1.3: Le note sul pianoforte
    ** Lezione 1.4: La diteggiatura
  * Modulo 2: Apprendimento degli accordi principali
    ** Lezione 2.1: Accordi maggiori
    ** Lezione 2.2: Accordi minori
    ** Lezione 2.3: Accordi diesis maggiori
    ** Lezione 2.4: Accordi diesis minori
  * Modulo 3: Suonare il pianoforte
    ** Lezione 3.1: Semplificare gli accordi: i rivolti
    ** Lezione 3.2: Applicare in pratica: "`No Woman No Cry`"
  * Esame finale
+
[options="header", cols="^.^20h, ^.^40, ^.^40a"]
.I contenuti del corso di pianoforte di livello base
|===
| Tipo di contenuto | Descrizione | Esempi

| Fatti (chiuso)
| Un insieme di dati dal carattere specifico e unico
| * I componenti dello strumento
  * Le note sul pianoforte
  * La diteggiatura
  * Accordi maggiori
  * Accordi minori
  * Accordi diesis maggiori
  * Accordi diesis minori


| Concetti (chiuso/aperto)
| Categoria che include al suo interno molteplici esemplificazioni
  * Semplificare gli accordi: i rivolti

| Principi (aperto)
| Indicazioni generali e linee guida
| * I principi fondamentali del pianoforte

|===

== Analisi dell'infrastruttura

Nei successivi paragrafi saranno valutati gli aspetti tecnologici e le risorse
umane disponibili.

=== Aspetti tecnologici

È utilizzata la piattaforma Moodle, piattaforma che copre il ruolo di LMS
(Learning Management System) e di LCMS (Learning Content Management System).
L'intero processo di creazione e gestione dei contenuti è supportato dal manuale
utente per i docenti. L'intero materiale sarà gestito come nodi ipertestuali
autosufficienti, che permetterà il riciclo di nodi tra vari corsi (se
necessario).

=== Disponibilità di risorse umane

Il docente del corso creerà e renderà disponibili tutti i materiali all'interno
della piattaforma. Sarà il docente (con l'eventuale assistenza di terzi, se
ritenuto necessario) a rispondere a richieste sui forum o nella chat e
correggerà gli eventuali esercizi a risposta aperta presenti all'interno del
corso.

== Tipologia di e-learning

La tipologia di e-learning adottata nel corso di pianoforte di livello base è
focalizzata sullo studente dell'accademia e adotta una terminologia semplice ma
il più possibile specifica. Su suppone che lo studente partecipi attivamente
alla vita della didattica partecipando mediante varie modalità alle
comunicazioni. Inoltre, il tutor (il docente) sarà sempre presente
nell'accompagnamento dello studente: il percorso si pone l'obiettivo di
raggiungere il livello di "`Applicazione`" (o di "`Comprensione`") della
tassonomia di Bloom e la presenza del docente è, quindi, necessaria.

In definitiva, la tipologia di e-learning stando alla classificazione di Mason è
quella del "`__Support Online Learning__`".

[options="header", cols="<.^h, <.^"]
|===
2+^| Support Online Learning
| Si focalizza | Sullo studente
| Si basa | Sulle attività
| È orientata all'apprendimento | In piccoli gruppi
| Interazione con il tutor | Significativa
| Collaborazione tra pari | Interazioni intense
|===

== Modalità di e-learning

La modalità di e-learning adottata è quella completamente a distanza _con_ il
supporto di un tutor (il docente). Quindi l'apprendimento avviene completamente
a distanza e gli studenti sono seguiti individualmente (o in gruppi) da un
tutor, che può avvalersi di strumenti di comunicazione sincrona o asincrona
offerti dalla piattaforma stessa (forum, chat, videoconferenza).
