[preface]
= Prefazione

:hide-uri-scheme:

Questo documento è la documentazione di progettazione del corso di
{course-name}. L'intero documento e il relativo corso sono scritti e gestiti da
{author}, che è possibile contattare personalmente all'indirizzo email {email}.

:!hide-uri-scheme:

La seguente progettazione ha quindi la funzione di spiegare in che modo sarà
sviluppato il corso di pianoforte di livello base. In questo corso ci si
occuperà di introdurre gli utenti allo strumento e fornire alcune metodologie e
tecniche d'uso di base che permettano allo studente di suonare composizioni già
conosciute o impararne autonomamente delle nuove.

Tale corso appartiene al più largo modulo "`Corso di Pianoforte`" che è
disponibile all'interno della piattaforma.

[#sect-moduli]
== Suddivisione in moduli

Il corso può essere suddiviso in quattro unità didattiche, riportate di seguito.

[#list-moduli]
. Introduzione allo strumento
. Utilizzare il pianoforte
. Leggere uno spartito
. Suonare il pianoforte
