= Definizione della macrotipologia didattica

La macrotipologia didattica, ovverosia la struttura complessiva del progetto, è
caratterizzata dalla scelta della tipologia di e-learning, dall'analisi
dell'utenza, del contenuto, dell'obiettivo e dell'infrastruttura. Quindi, si
analizzano i vincoli di ingresso e le loro relazioni per la produzione del
presente documento di lavoro.

== Analisi dei vincoli di ingresso e delle relazioni

=== Analisi dell'utenza

Gli utenti a cui è rivolto il corso di batteria di livello base possono avere età e competenze differenti, l'importante è che siano interessati a imparare a suonare questo strumento . Sono stati presi in esame diversi aspetti (che sono stati discussi nelle sezioni seguenti) per comprendere quali sono le caratteristiche dei potenziali utenti.

==== Distanza fisica

Gli utenti possono essere dislocati in varie parti del mondo, ma ovviamente, in quanto sarà un corso sviluppato in italiano, sarà necessaria la conoscenza e buona padronanza della lingua italiana. Molte terminologie di base relative alla batteria sono in lingua inglese, quindi è necessaria una minima conoscenza e una minima padronanza di questa lingua, in modo da pronunciare correttamente la terminologia. 
Inoltre, sia per problematiche legate alla disponibilità temporale degli utenti, per la loro potenziale locazione geografica ma anche per la questione pandemica che si sta vivendo, non è possibile presupporre la possibilità di partecipare alle attività fisicamente in sede. Per questo motivo l'utente, accedendo alla piattaforma, deve poter usufruire del materiale didattico in qualisiasi momento. Inoltre, il fattore della distanza fisica agisce direttamente sugli incontri in presenza organizzabili, che devono essere necessariamente sostituiti da incontri online.

==== Numero

Il numero degli utenti non è prevedibile a priori. Per questo motivo il
materiale didattico deve essere fruibile senza limiti di utenti attivi
contemporaneamente. Una eccezione riguarda gli incontri online organizzati:
qualora il numero di iscritti al corso fosse ingestibile per una singola
conferenza, è possibile suddividere il gruppo in gruppi di lavoro con cui
organizzare singolarmente degli incontri, questo nel caso in cui ci sia bisogno di effettuare un workshop con tutti gli allievi in un unico incontro.
Nel caso in cui, invece, è necessario l'incontro online per perfezionare determinate tecniche e/o la postura dell'allievo, e quindi di ricevimento per ulteriori chiarimenti, sarà necessario avere una video lezione online con il singolo studente in quanto lo strumento che si andrà a imparare creerebbe confusione tra i partecipanti.

==== Accesso dell'utente alla tecnologia

Le competenze e conoscenze informatiche degli utenti sono varie, ma tutti
conoscono almeno come si utilizza un browser internet. Non sono necessarie
configurazioni di alcun tipo, quindi agli utenti non è richiesto alcuna
competenza specifica. Nel caso in cui gli allivi sono bambini, sarà necessario il supporto di un genitore in modo da collegare il bambino alla piattaforma (anche se al giorno d'oggi questa tipologia di allievi utilizzato internet da quando hanno capacità motoria e mentale sufficiente).
L'unico prerequisito "`tecnologico`" del corso è l'accesso
a una batteria (o una batteria elettronica) oppure a un qualsiasi tipo di percussione per poter iniziare a fare pratica.

==== Expertise di dominio dell'utente

Essendo questo un corso di batteria di livello base, si presuppone che i partecipanti non hanno mai avuto alcun contatto con questo strumento (almeno per una buona parte, in quanto possono essere interessati degli autodidatti). Inoltre, nel caso in cui ci fosse necessità di una terminologia riguardante la teoria musicale di base, verrà fornito un vocabolario di base minimo che permetta la comunicazione, ma tale vocabolario non deve e non può sostituire un corso di teoria musicale di base, che resta un prerequistito consigliato del corso.

==== Omogeneità o disomogeneità di interesse tra i partecipanti

L'interesse medio sarà omogeneo in quanto tutti i partecipanti scelgono
liberamente di iscriversi al corso in base alle proprie preferenze e
alle proprie inclinazioni. Inoltre, al superamento di una prova finale, sarà
consegnato ai partecipanti un attestato di partecipazione e superamento del
corso: questo terrà vivo l'interesse dei partecipanti.

==== Disponibilità del partecipante alla condivisione e alla collaborazione

Il partecipante, nel suo interesse, sarà invogliato alla collaborazione con
altri iscritti per approfondire argomenti, chiarire dubbi, risolvere problemi e
confrontarsi. Tali comunicazioni possono avvenire mediante gli strumenti
disposti dalla piattaforma (forum, chat, ecc.) ma anche con modalità esterne
(social network, software di _Instant Messaging_, ecc.)

== Analisi dell'obiettivo

Gli obiettivi formativi sono definiti utilizzando la _tassonomia di Bloom_ al
fine di categorizzare gli obiettivi educativi nel dominio conoscitivo, che
riguarda le attività intellettuali e logiche. Tale dominio viene suddiviso nei
seguenti obiettivi didattici, ordinati di seguito dal più semplice al più
complesso: _Conoscenza_, _Comprensione_, _Analisi_, _Applicazione_, _Sintesi_ e
_Valutazione_.

Il corso si pone l'obiettivo di raggiungere il livello di Applicazione. Nelle
seguenti sezioni si riportano gli obiettivi e le motivazioni dei tre livelli
coperti dal corso.

Conoscenza:: L'utente deve essere in grado di rievocare il materiale memorizzato
e richiamare alla memoria fatti, metodi e processi. Per verificare la
correttezza della conoscenza acquisita dallo studente, al termine delle attività
didattiche, saranno inseriti dei brevi test di autovalutazione (nelle forme di
domande a risposta multipla e/o test vero/falso).

Comprensione:: L'utente deve essere in grado di afferrare il senso delle
informazioni e di saperle trasformare. Pertanto, per favorire l'acquisizione e
l'estrapolazione delle informazioni saranno inserite durante le lezioni delle
immagini, degli esempi, dei grafici e/o dei video che accompagnino la spiegazione. Ogni
studente deve quindi essere in grado di rispondere a domande poste in maniera
differente rispetto a quanto riportato all'interno del materiale didattico.

Applicazione:: L'utente deve essere in grado di utilizzare il materiale
conosciuto per risolvere problemi nuovi e deve inoltre saper utilizzare
rappresentazioni astratte in casi concreti. Nel caso specifico dello strumento
musicale, lo studente deve essere in grado di utilizzare in pratica ciò che ha
studiato dal materiale didattico astratto e deve inoltre essere in grado di
utilizzare le tecniche apprese in nuovi contesti (per esempio, imparando
autonomamente a suonare una ritmica nuova). Ai fini della valutazione di
questo aspetto, al termine del corso lo studente dovrà affrontare un esame in
cui non solo gli verranno poste delle domande nuove legate al materiale
didattico, ma dovrà partecipare a una conferenza con il docente per valutare la
sua capacità di suonare effettivamente lo strumento con ritmiche nuove.

Si sottolinea che non tutti i moduli (elencati nella sezione
"`<<sect-moduli>>`") potrebbero avere la necessità di coprire tutti i tre
livelli: in alcuni casi può essere sufficiente fermarsi a un livello inferiore.
I casi specifici per ogni lezione sono riportati nella <<tab-lezioni-bloom>>.

[#tab-lezioni-bloom]
[options="header", cols="^.^10h,^.^15,^.^25a,^.^20,^.^20a", stripes=even]
.Attività, obiettivi e livelli della tassonomia di Bloom per ogni modulo
|===
| N.ro Modulo | Titolo modulo | Attività | Obiettivo | Tassonomia di Bloom

| 1
| Introduzione allo strumento
| * Conoscenza delle componenti principali dello strumento, dei suoi principi
  fondamentali e l'importanza dell'impugnatura della bacchetta
| Lo studente deve conoscere quali sono le componenti fondamentali dello
  strumento che sta utilizzando e deve conoscere quali sono le "`regole`" e i
  principi basilari della disciplina
| * Conoscenza

| 2
| Rudimenti
| * Comprendere cosa sono i rudimenti
  * Comprendere quali sono i rudimenti di base
  * Applicazione della teoria dei rudimenti per poter iniziare a riprodurli sulla percussione scelta (o direttamente sulla batteria, o su un pad)
| Lo studente deve essere in grado di comprendere cosa sono i rudimenti, quali sono quelli di base e deve essere in grado di applicare i rudimenti suonandoli su una batteria (o su un pad, o su una qualsiasi percussione)
| * Conoscenza
  * Comprensione
  * Applicazione

| 3
| Accenti
| * Comprendere cosa sono gli accenti
  * Comprendere quali sono gli accenti
  * Applicare questi accenti riproducendoli su una batteria (o su un pad, o su una qualsiasi percussione)
| Lo studente deve essere in grado comprendere cosa sono gli accenti e quali sono quelli fondamentali.
  Deve essere inoltre in grado di riprodurre gli accenti studiati su una batteria (o su un pad, o su una qualsiasi percussione)
| * Conoscenza
  * Comprensione
  * Applicazione
|===

== Analisi del contenuto

I contenuti del corso sono analizzati in base alle seguenti caratteristiche:

Apertura o chiusura:: Il contenuto è principalmente (ma non totalmente) chiuso,
in quanto trattasi di fatti e concetti. Tuttavia vi sono alcune eccezioni in cui
i contenuti risultano aperti in quanto principi o processi.

Stabilità o instabilità:: I contenuti delle lezioni sono stabili, in quanto il
corso tratta di argomenti ben radicati nell'ambito musicale. È possibile
prevedere aggiornamenti futuri, dovuti all'avanzamento della materia, ma è poco
probabile che tali aggiornamenti riguardino le tecniche e i principi di base
trattati in questo corso.

Testualità, multimedialità e interattività:: Le lezioni si presentano nella
forma di ipertesti multimediali comprensivi, quindi, di testo, immagini, video
e/o animazioni. L'interattività è espressa mediante l'uso di hyperlink (tipici
negli ipertesti) e dei test complessivi. Saranno presenti test al termine di
ogni lezione, utili ai fini di un'autovalutazione, e dei test
complessivi che servono a valutare lo studente per considerare il corso completo
e superato.
Inoltre, saranno presenti dei test al termine di ogni singolo modulo, utili ai fini di un'autovalutazione e di propedeuticità al modulo successivo in modo da rendere l'allievo consapevole di poter o meno proseguire con l'apprendimento passando al modulo successo.

[#sect-lezioni]
=== Suddivisione del corso in lezioni

* Modulo 1: Introduzione allo strumento
  ** Lezione 1.1: Struttura dello strumento
  ** Lezione 1.2: I concetti fondamentali della batteria
  ** Lezione 1.3: Impugnatura della bacchetta
* Modulo 2: Rudimenti cosa sono e quali sono
  ** Lezione 2.1: Introduzione ai rudimenti
  ** Lezione 2.2: Quali sono i rudimenti
  ** Lezione 2.3: Propedeuticità dei rudimenti
* Modulo 3: Accenti cosa sono e quali sono
  ** Lezione 3.1: Introduzione agli accenti
  ** Lezione 3.2: Diversi tipi di accenti
* Esame finale

[options="header", cols="^.^20h, ^.^40, ^.^40a"]
|===
| Tipo di contenuto | Descrizione | Esempi

| Fatti (chiuso)
| Un insieme di dati dal carattere specifico e unico
| * Struttura dello strumento
  * Introduzione ai rudimenti
  * Introduzione agli accenti
| Concetti (chiuso/aperto)
| Categoria che include al suo interno molteplici esemplificazioni
| * L'impugnatura della bacchetta
  * Quali sono i rudimenti
  * Propedeuticità dei rudimenti
  * Diversi tipi di accenti
| Principi (aperto)
| Indicazioni generali e linee guida
| * I principi fondamentali della batteria
|===

== Analisi dell'infrastruttura

Nei successivi paragrafi saranno valutati gli aspetti tecnologici e le risorse
umane disponibili.

=== Aspetti tecnologici

È utilizzata la piattaforma Moodle, piattaforma che copre il ruolo di LMS
(Learning Management System) e di LCMS (Learning Content Management System).
L'intero processo di creazione e gestione dei contenuti è supportato dal manuale
utente per i docenti. L'intero materiale sarà gestito come nodi ipertestuali
autosufficienti, che permetterà il riciclo di nodi tra vari corsi (se
necessario).

=== Disponibilità di risorse umane

Il docente del corso creerà e renderà disponibili tutti i materiali all'interno
della piattaforma. Sarà il docente (con l'eventuale assistenza di terzi, se
ritenuto necessario) a rispondere a richieste sui forum o nella chat e
correggerà gli eventuali esercizi a risposta aperta presenti all'interno del
corso.

== Tipologia di e-learning

La tipologia di e-learning adottata nel corso di batteria di livello base è
focalizzata sullo studente dell'accademia e adotta una terminologia semplice ma
il più possibile specifica. Si suppone che lo studente partecipi attivamente
alla vita della didattica partecipando mediante varie modalità alle
comunicazioni. Inoltre, il tutor (il docente) sarà sempre presente
nell'accompagnamento dello studente: il percorso si pone l'obiettivo di
raggiungere il livello di "`Applicazione`" della tassonomia di Bloom e la
presenza del docente è, quindi, necessaria.

In definitiva, la tipologia di e-learning stando alla classificazione di Mason è quella del _"`Support Online Learning`"_.

[options="header", cols="<.^h, <.^"]
|===
2+^| Support Online Learning
| Si focalizza | Sullo studente
| Si basa | Sulle attività
| È orientata all'apprendimento | In piccoli gruppi
| Interazione con il tutor | Significativa
| Collaborazione tra pari | Interazioni intense
|===

== Modalità di e-learning

La modalità di e-learning adottata è quella completamente a distanza _con_ il
supporto di un tutor (il docente). Quindi l'apprendimento avviene completamente
a distanza e gli studenti sono seguiti individualmente (o in gruppi) da un
tutor, che può avvalersi di strumenti di comunicazione sincrona o asincrona
offerti dalla piattaforma stessa (forum, chat, videoconferenza).
