= Analisi della piattaforma: forma.lms

== Installazione

== Features

Layout reattivo:: L'incredibile successo commerciale di smartphone e di altri vari 
dispositivi hanno obbligato i designer a fronteggiare il problema delle differenti 
risoluzioni dei monitor. Proprio per queste continue evoluzioni della tecnologia i
siti web devono essere reattivi. La piattoforma fornisce un layout reattivo e 
un'interfaccia nuovissima con aspetto moderno progettata per un'esperienza utente 
facile e coinvolgente.

Controllo totale sui corsi:: Un'ottima caratteristica per un sito di E-learning è la
possibilità di gestire i corsi. La piattoforma, appunto, fornisce i mezzi necessari 
per la gestione degli insegnamenti e della condivisione dei suoi materiali. Permette,
inoltre, di monitorare le attività con un sistema di tracciamento avanzato e compatibilità SCORM.

Certificati PDF automatici:: L'apprendimento formale, un tipo di apprendimento che si 
sviluppa nell’ambito di un contesto strutturato e organizzato, conduce ad una forma
di riconoscimento ufficiale.
La piattaforma permette la generazione automatica di certificati PDF al completamento 
dei corsi, con modelli grafici personalizzabili illimitati.

E-commerce integrato:: La piattaforma presenta una funzionalità di e-commerce 
integrata che permette di vendere i propri corsi con facilità, senza preoccuparsi
di adottare soluzioni esterne. 

Notifiche automatiche:: La piattaforma presenta un sistema di notifica automatico
in grado di avvisare quando l'utente compie un azione rilevante:
la sua registrazione, l'iscrizione o il completamento di un corso.
Le notifiche possono essere inviate via sms o tramite e-mail.
Nel caso di alcuni tipi di notifiche è possibile impostare quanto prima/dopo devono
essere inviate, oltre che a messaggi personalizzati.

Comunicazione tra utenti:: La piattaforma consente agli utenti registrati di 
comunicare attraverso l'utilizzo di forum, permettendo a coloro che sono registrati
agli stessi corsi di interagire tra loro. Inoltre è presente un sistema di messaggistica
privato.

Multi-Client:: È possibile gestire diversi template e diversi URL per mostrare a
ciascun client una piattaforma diversa con una singola installazione di
forma.lms. Questa feature è potenzialmente utile se, per esempio pensando al
contesto universitario (si veda <<formalms-possibili-contesti-duso>>), si vuole
gestire un'unica installazione di forma.lms (quella dell'università) da dividere
in più piattaforme (quelle dei dipartimenti). 
 
Estensibile attraverso plugins:: Se la piattaforma non consente di gestire delle
operazioni che sono necessarie per il sistema che si sta progettando, è
possibile estendere le funzionalità di forma.lms attraverso plugin e script
personalizzati. Se non dovesse essere disponibile un plugin che gestisca
l'operazione necessaria, è pur sempre possibile realizzarne uno _ad-hoc_.
+
Caricare un plugin è, inoltre, molto semplice: basta effettuare l'accesso alla
piattaforma (come amministratore), andare nella pagina di amministrazione e
scegliere dal menu la voce "`Configurazione > Plugin`".

Integrazione:: È possibile integrare la piattaforma di e-learning con il proprio
software gesionale attraverso API native e connettori, rendendo quindi il
sistema creato con forma.lms parte del proprio ecosistema digitale.

[#formalms-possibili-contesti-duso]
== Possibili contesti d'uso

L'LMS _forma.lms_ risulta essere molto versatile. È infatti possibile utilizzarlo
per diversi contesti. Di seguito se ne riportano tre, ritenuti più utili.

Università:: Le features di forma.lms si adattano bene al contesto universitario.
La gestione dei corsi e degli utenti permette di mappare in modo naturale il
mondo delle lezioni accademiche a quello del LMS. Inoltre, la gestione
automatica di certificati consente anche la generazione di attestati di laurea
al termine del percorso di studi, consentendo in modo molto semplice la
creazione di un'intera facoltà online. Inoltre, la gestione dei _webinar_ (con
relativi attestati) consente di tenere seminari online, simulando l'ambiente
universitario.

Accademie di varia tipologia:: Le features di forma.lms si adattano ai contesti
di accademie di varia tipologia (per esempio, accademie musicali). È quindi
possibile gestire diversi corsi (per esempio, nel caso di accademie musicali, è
possibile creare un corso per ogni strumento e grado di conoscenza necessaria).
Anche in questo caso, la gestione automatica dei certificati permette di
rilasciare certificazioni più o meno ufficiali di superamento o frequenza dei
corsi. Il tutto si incastra perfettamente con il motore di e-commerce incluso in
forma.lms che consente di limitare l'accesso ai corsi previo pagamento.

Scuole private e/o professionali:: Le features di e-commerce di forma.lms sono
perfette per il mondo delle scuole private e/o professionali. Si permette quindi
di creare dei corsi accessibili a pagamento (con rilascio di certificati).
Inoltre, è possibile tenere seminari di formazione (si pensi a un possibile
seminario di sicurezza sul lavoro) anch'essi a pagamento (o gratuiti) senza
alcuna difficoltà.

Condivisione delle conoscenze:: Le features di forma.lms permettono di costruire
un sistema che funga da luogo di incontro tra diversi utenti: è infatti
possibile progettare e realizzare (con uno sforzo relativamente piccolo) un
sistema che consenta agli utenti stessi di creare corsi e seminari, a pagamento
e non, e di usufruirne. Inoltre è possibile rilasciare certificati di
partecipazione (generati automaticamente). Questo tipo di contesto è altamente
competitivo dal punto di vista commerciale e un sistema simile si affiancherebbe
a sistemi già esistenti come https://www.udemy.com/[Udemy],
https://www.coursera.org/[Coursera], https://www.skillshare.com/[SkillShare],
https://www.docety.com/[Docety] e altri.
