= Analisi della piattaforma: forma.lms

== Installazione

L'installazione è molto semplice in quanto forma.lms mette a disposizione un
tool automatico che si avvia appena si entra per la prima volta nel sito.

Di seguito si riportano i passaggi da seguire per procedere all'installazione
della piattaforma sul computer locale utilizzando la piattaforma
https://www.apachefriends.org/it/index.html[XAMPP]:

. *Download di forma:* Il primo passaggio riguarda il download del pacchetto che
contiene forma. Basta visitare il sito
https://www.formalms.org/download.html[FormaLMS] e cliccare sul puslante di
Download.

. *Estrazione del pacchetto:* Una volta scaricato il pacchetto
`formalms-v2.x.y.z.zip` (il nome del file può variare in base alla versione che
si sta scaricando) basta estrarre la cartella `formalms` all'interno di un
webserver (ad esempio nella cartella `htdocs`, nel caso di un server XAMPP).

. *Creazione del database:* Una volta copiata la cartella all'interno del
webserver, basta avviare i servizi dal pannello di controllo dello stesso per
poi visitare il link http://localhost/phpmyadmin da cui si può creare un
database che verrà richiesto durante l'installazione di forma.

. *Installazione di forma:* Adesso basta visitare il link
http://localhost/formalms/install/ e seguire i passaggi dell'installazione
automatica.

. *Modifiche finali per la sicurezza:* Una volta terminata l'installazione si
consiglia di recarsi all'interno di `formalms`, cartella copiata precedentemente
nel webserver, per poi cancellare la cartella `install`.

Seguiti i passaggi è possibile utilizzare la piattaforma sul proprio pc locale.

== Features

Layout reattivo:: L'incredibile successo commerciale di smartphone e di altri
vari dispositivi hanno obbligato i designer a fronteggiare il problema delle
differenti risoluzioni dei monitor. Proprio per queste continue evoluzioni della
tecnologia i siti web devono essere reattivi. La piattoforma fornisce un layout
reattivo e un'interfaccia nuovissima con aspetto moderno progettata per
un'esperienza utente facile e coinvolgente.

Controllo totale sui corsi:: Un'ottima caratteristica per un sito di E-learning
è la possibilità di gestire i corsi. La piattoforma, appunto, fornisce i mezzi
necessari per la gestione degli insegnamenti e della condivisione dei suoi
materiali. Permette, inoltre, di monitorare le attività con un sistema di
tracciamento avanzato e compatibilità SCORM.

Certificati PDF automatici:: L'apprendimento formale, un tipo di apprendimento
che si sviluppa nell’ambito di un contesto strutturato e organizzato, conduce ad
una forma di riconoscimento ufficiale. La piattaforma permette la generazione
automatica di certificati PDF al completamento dei corsi, con modelli grafici
personalizzabili illimitati.

Creazione di Webinar:: La piattaforma form.lms supporta il webinar (WEB
semINAR), ovvero seminario online. Grazie ad esso, si ha la comodità di
partecipare a videoconferenze da casa con l'efficacia e l'interattività tipiche
di un evento in presenza (_che possono essere lezioni, seminari, riunioni,
etc..._). Il webinar è uno strumento che sfrutta la modalità sincrona, ma può
essere sfruttato in modalità asincrona attraverso la registrazione dell'evento
per poi essere visionato in ore o giorni differenti. Un altro vantaggio per chi
organizza una videoconferenza è quello di poter illustrare, ai partecipanti
della stessa,  slides e documenti in diretta.

Gestione flessibile degli utenti:: Gli utenti possono essere organizzati,
attraverso organigrammi, in gruppi o in base a ruoli. È possibile gestire gli
amminastratori assegnandoli autorizzazioni speciali. Inoltre, un altro vantaggio
è quello di poter importare, esportare e modificare più utenti con un solo clic.

Report personalizzati:: La piattaforma permette di creare facilmente
innumerevoli report personalizzati attraverso un semplice wizard che guida
l'utente passo dopo passo. Inoltre, si ha la possibilità di pianificare l'invio
regolare di questi report agli amministratori e/o agli utenti presenti nel
corso.

Ruoli e competenze:: È possibile creare delle competenze che possono essere
assegnate agli utenti. Ogni competenza può essere impostata a "`Punteggio`" o
essere semplicemente assegnata. Inoltre la piattaforma mette a disposizione più
tipologie che si dividono in: Competenze, Attitudini e Conoscenze. Oltre alle
competenze c'è la possibilità di creare dei Gruppi e ad ogni gruppo si possono
creare dei Ruoli. Ogni ruolo può essere assegnato a uno o più utenti e può
contenere una o più competenze che sono assegnate automaticamente ad ogni utente
inserito.

Aule:: La piattaforma permette di creare più corsi, divisibili in macro-gruppi,
che possono contenere uno o più utenti. Ogni corso può essere duplicato
permettendo di creare più "`Aulee`" dello stesso corso con gli stessi contenuti
ma utenti diversi.

Cataloghi e corsi:: I corsi possono essere divisi in categorie permettendo di
organizzarli. Si possono creare anche categorie e percorsi formativi, per
offrire agli utenti diverse scelte di formazione.

E-commerce integrato:: La piattaforma presenta una funzionalità di e-commerce
integrata che permette di vendere i propri corsi con facilità, senza
preoccuparsi di adottare soluzioni esterne. 

Notifiche automatiche:: La piattaforma presenta un sistema di notifica
automatico in grado di avvisare quando l'utente compie un azione rilevante: la
sua registrazione, l'iscrizione o il completamento di un corso. Le notifiche
possono essere inviate via sms o tramite e-mail. Nel caso di alcuni tipi di
notifiche è possibile impostare quanto prima/dopo devono essere inviate, oltre
che a messaggi personalizzati.

Comunicazione tra utenti:: La piattaforma consente agli utenti registrati di
comunicare attraverso l'utilizzo di forum, permettendo a coloro che sono
registrati agli stessi corsi di interagire tra loro. Inoltre è presente un
sistema di messaggistica privato.

Multi-Client:: È possibile gestire diversi template e diversi URL per mostrare a
ciascun client una piattaforma diversa con una singola installazione di
forma.lms. Questa feature è potenzialmente utile se, per esempio pensando al
contesto universitario (si veda <<formalms-possibili-contesti-duso>>), si vuole
gestire un'unica installazione di forma.lms (quella dell'università) da dividere
in più piattaforme (quelle dei dipartimenti). 
 
Estensibile attraverso plugins:: Se la piattaforma non consente di gestire delle
operazioni che sono necessarie per il sistema che si sta progettando, è
possibile estendere le funzionalità di forma.lms attraverso plugin e script
personalizzati. Se non dovesse essere disponibile un plugin che gestisca
l'operazione necessaria, è pur sempre possibile realizzarne uno _ad-hoc_.
+
Caricare un plugin è, inoltre, molto semplice: basta effettuare l'accesso alla
piattaforma (come amministratore), andare nella pagina di amministrazione e
scegliere dal menu la voce "`Configurazione > Plugin`".

Integrazione:: È possibile integrare la piattaforma di e-learning con il proprio
software gesionale attraverso API native e connettori, rendendo quindi il
sistema creato con forma.lms parte del proprio ecosistema digitale.

[#formalms-possibili-contesti-duso]
== Possibili contesti d'uso

L'LMS _forma.lms_ risulta essere molto versatile. È infatti possibile utilizzarlo
per diversi contesti. Di seguito se ne riportano tre, ritenuti più utili.

Università:: Le features di forma.lms si adattano bene al contesto universitario.
La gestione dei corsi e degli utenti permette di mappare in modo naturale il
mondo delle lezioni accademiche a quello del LMS. Inoltre, la gestione
automatica di certificati consente anche la generazione di attestati di laurea
al termine del percorso di studi, consentendo in modo molto semplice la
creazione di un'intera facoltà online. Inoltre, la gestione dei _webinar_ (con
relativi attestati) consente di tenere seminari online, simulando l'ambiente
universitario.

Accademie di varia tipologia:: Le features di forma.lms si adattano ai contesti
di accademie di varia tipologia (per esempio, accademie musicali). È quindi
possibile gestire diversi corsi (per esempio, nel caso di accademie musicali, è
possibile creare un corso per ogni strumento e grado di conoscenza necessaria).
Anche in questo caso, la gestione automatica dei certificati permette di
rilasciare certificazioni più o meno ufficiali di superamento o frequenza dei
corsi. Il tutto si incastra perfettamente con il motore di e-commerce incluso in
forma.lms che consente di limitare l'accesso ai corsi previo pagamento.

Scuole private e/o professionali:: Le features di e-commerce di forma.lms sono
perfette per il mondo delle scuole private e/o professionali. Si permette quindi
di creare dei corsi accessibili a pagamento (con rilascio di certificati).
Inoltre, è possibile tenere seminari di formazione (si pensi a un possibile
seminario di sicurezza sul lavoro) anch'essi a pagamento (o gratuiti) senza
alcuna difficoltà.

Condivisione delle conoscenze:: Le features di forma.lms permettono di costruire
un sistema che funga da luogo di incontro tra diversi utenti: è infatti
possibile progettare e realizzare (con uno sforzo relativamente piccolo) un
sistema che consenta agli utenti stessi di creare corsi e seminari, a pagamento
e non, e di usufruirne. Inoltre è possibile rilasciare certificati di
partecipazione (generati automaticamente). Questo tipo di contesto è altamente
competitivo dal punto di vista commerciale e un sistema simile si affiancherebbe
a sistemi già esistenti come https://www.udemy.com/[Udemy],
https://www.coursera.org/[Coursera], https://www.skillshare.com/[SkillShare],
https://www.docety.com/[Docety] e altri.
