= Progettazione ambiente

== Fase preliminare

=== Analisi dei bisogni

Il committente è un'accademia musicale ("`X`"). Il sistema deve essere una
piattaforma di e-learning per tale accademia. L'accademia ("`X`") richiede una
strutturazione della piattaforma semplice, in modo tale da ridurne al minimo la
curva di apprendimento. È stato richiesto di avere un unico corso per singolo
strumento, nel quale sia possibile suddividere gli studenti in gruppi diversi
(per esempio, per età in modo da non rendere difficile la comunicazione tra
docenti e studenti).

L'accademia ha espresso la necessità di avere un ambiente per i propri studenti
che funda da supporto, sostegno e anche di rimpiazzo ai suoi corsi tenuti nella
struttura della scuola. I bisogni evidenziati sono vari, tra cui:

* L'organizzazione sente la necessità di far proseguire le lezioni (e gli
  studenti sentono la necessità di continuare a usufruirne) in un periodo di
  emergenza internazionale, in modo da ridurre i rischi di contagio (rispettando
  le ordinanze attuali) e da limitare l'impatto sul piano economico.
* Si vuole permettere agli studenti lavoratori (o in altro modo impossibilitati
  alla frequenza fisica dei corsi) di coltivare le proprie passioni e migliorare
  costantemente le proprie abilità.
* Si vuole permettere di adattare il processo di apprendimento alle proprie
  caratteristiche e modalità di apprendimento.
* Si vuole permettere di approfondire argomenti che non sono stati trattati
  durante le lezioni frontali riguardanti, ad esempio, la teoria musicale.
* Si vuole favorire un'erogazione rapida dei contenuti didattici in modo rapido,
  raggiungendo tutti i partecipanti di un ipotetico corso con una sola azione.

Il sistema va quindi inserito all'interno del contesto di un'accademia musicale
e deve supportare gli studenti in modo da poterli arricchire con qualsiasi mezzo
comunicativo. In tale contesto, tutti gli studenti sono pienamente consepevoli
del percorso di studi intrapreso e della quantità di tempo e impegno necessaria
a completarlo. Inoltre, deve essere garantita un buon grado di ufficialità del
percorso di studi, rilasciando certificati.

L'obiettivo principale che la piattaforma si propone di conseguire è, quindi,
quello di fornire agli studenti la possibilità di studiare a prescindere dalla
disponibilità temporale e dalla locazione geografica. Gli obiettivi specifi sono
poi vari in base allo specifico corso. 

I corsi possono essere divisi in due macrocategorie: teorici (teoria musicale) e
pratici (imparare uno strumento musicale).

Gli obiettivi principali per un corso teorico riguardano:

* L'erogazione dei contenuti legati all'aspetto teorico musicale.
* L'apprendimento dei concetti base e fondamentali per il coseguimento di
  qualsiasi altro percorso pratico e/o teorico.
* L'apprendimento dei concetti di teoria avanzata.
* L'approfondimento di argomenti aggiuntivi per lo studente che ritiene egli
  stesso interessante e stimolante per la sua conoscenza.
* Il ripasso di argomenti che con il tempo lo studente che ritiene di non
  ricordare alla perfezione, per esempio dimenticando la terminologia, un
  concetto base, come eseguire un esercizio eccetera (oppure può essere lo
  stesso docente a indicare allo studente quali argomenti è necessario che
  ripassi).

Gli obiettivi principali per un corso pratico, invece, riguardano:

* L'insegnamento di tecniche basilari per il primo approccio allo strumento
  scelto da parte dell'allievo.
* L'insegnamento di tecniche specifiche di esecuzione di un determinato
  virtuosismo (ad esempio il _tapping_, una tecnica per la chitarra).
* L'erogazione di contenuti (che possono essere documenti testuali, video,
  oppure spartiti) riguardanti le tecniche e/o l'esecuzione dei brani che il
  docente vuole insegnare ai suoi studenti. In questo modo il docente potrà
  mostrare ai suoi studenti tutte le varie caratteristiche del brano proposto.

=== Caratterizzazione della comunità

Il sistema commissionato è una piattaforma di e-learning in cui l'accademia può
spostare la propria didattica: la comunità su cui si basa è la stessa comunità
che partecipa alla didattica in sede. La comunità può, quindi, essere divisa in
due gruppi: gli "`allievi`" (coloro che usufruiscono della didattica) e i
"`maestri`". In questi due macrogruppi è, inoltre, possibile individuare alcuni
sottogruppi: gli allievi possono essere suddivisi per competenze e fasce di età;
i maestri possono essere divisi per aree di competenza. In generale, i membri
della comunità sono tutti accumunati dal proprio dominio di conoscenza: la
musica. In tale campo, tutti i membri sono interessati (in varia misura) a
migliorare le proprie conoscenze e abilità. Problematiche comuni da affrontare
con una comunità di questo tipo sono riguardanti la padronanza di linguaggio
(sia tecnico che non: si pensi alla differenza nella capacità di esprimersi e
comprendere che si ha tra un bambino e un adulto) e la differenza nei tempi da
dedicare all'apprendimento.

Il campo musicale e, più in piccolo, le conoscenze e competenze che l'accademia
ha l'obiettivo di fornire ai propri allievi sono oggetti ben codificati: è
possibile strutturare l'intera conoscenza in tale ambito con una struttura ad
albero (riportato in <<img-dominio-conoscenza>>).

Non è prevista un'area geografica in cui circoscrivere le provenienze dei membri
della comunità ma, data la natura tendenzialmente circoscritta (nelle sue fasi
primordiali) di un'accademia musicale, si presuppone che tutti i membri della
comunità parlino la lingua italiana, lingua in cui saranno erogati i corsi.
Questo ambiente permette, anzi, di avere studenti e docenti collocati in luoghi
differenti in modo da congiungere passione, studio e voglia di imparare
argomenti nuovi. Ciò risulta essere una risorsa fondamentale per l'accademia, in
quanto è possibile avere contatti con esperti musicali normalmente
impossibilitati a recarsi nella struttura della stessa accademia dando loro la
possibilità di fornire il proprio contributo per l'esperienza e bagaglio
culturale degli allievi.

Non è possibile prevedere delle capacità informatiche della comunità, data la
diversità di età e percorsi seguiti, tuttavia si pressupone che tutti i membri
abbiano una competenza di base nell'utilizzo di un browser internet.

Attualmente, in sede, si possono tenere lezioni sia di gruppo che individuali ed
è possibile collaborare incontrandosi. Inoltre, gli allievi sono liberi di
contattarsi a piacere con varie metodologie. Le lezioni sono tutte in sede e le
comunicazioni possono avvenire sia online che non. Più in dettaglio, le
comunicazioni online sono principalmente sincrone (mediante _chat_ utilizzando
sistemi come WhatsApp, Telegram, Facebook, etc), ma possono anche essere
asincrone. La piattaforma deve quindi dare la possibilità a tutti i suoi membri
di comunicare, utilizzando forum, comunicazioni in broadcast, chat (con
eventuali caffè virtuali). Tali comunicazioni possono riguardare, per esempio,
notifiche varie da parte dei docenti, organizzazione di saggi, confronto fra gli
alunni etc. Deve inoltre essere possibile gestire video conferenze, per favorire
l'attività didattica.

== Dimensione gestionale

=== Flussi di comunicazione

L'interazione fra studenti e docenti può, attualmente, avvenire mediante scambi
verbali e condivisione di documenti. Per questo motivo, la piattaforma deve
fornire la possibilità di gestire entrambe le forme di comunicazione. In
particolare, per gli scambi verbali devono essere disponibili forum, chat, video
conferenze, etc. Per quanto riguarda lo scambio di documenti, deve essere
possibile per i docenti fornire del materiale ai propri studenti e, per
quest'ultimi, usufruirne e condividerne di nuovo. Le metodologie specifiche
circa l'erogazione dei contenuti e sulle modalità di comunicazione sono quindi
varie e saranno i docenti e i loro studenti a decidere quali adottare e
utilizzare.

La comunità è interamente gestita dalla segreteria dell'accademia, per cui i
suoi membri non devono prendere decisioni. Più nel dettaglio, ai docenti saranno
attribuiti i corsi d'ufficio (quindi è previsto un solo corso per ogni tipologia
di argomento) e gli studenti seguiranno il percorso didattico del corso a cui si
iscrivono. Quindi, riassumento, le uniche decisioni che i membri devono prendere
riguardano i corsi a cui iscriversi (per gli studenti), la definizione del
percorso didattico (per i docenti) e eventuali decisioni che i docenti decidono
di lasciare agli studenti (che non è possibile prevedere a priori).

Data l'alta strutturazione delle conoscenze del dominio musicale (si veda
<<img-dominio-conoscenza>>), il modo migliore per alimentare la base di
conoscenza della comunità è quello di organizzare e classificare le discussioni
e il materiale in base all'argomento trattato, lasciando la possibilità allo
studente di scegliere il livello di dettaglio a cui arrivare, per poi lasciare
al docente l'onere di valutare se lo studente ha raggiunto il suo obiettivo
(ovverosia il livello precedentemente prefissato mediante la scelta del corso).

=== Definizione della conoscenza comunitaria

[#img-dominio-conoscenza]
.Mappa concettuale dominio di conoscenza. Con "`Strumento`" si intende un qualsiasi strumento musicale (per esempio, chitarra o pianoforte): la stessa struttura riportata è presente a prescindere dallo specifico strumento preso in esame.
[blockdiag, mappa-dominio-conoscenza, svg] 
....
blockdiag {
  START[label="La Musica"];
  T[label="Teoria"];
  S[label="Pratica"];
  TB[label="Teoria Base"];
  TA[label="Teoria Avanzata"];
  SP[label="Strumento"];
  SPB[label="Livello Base"];
  SPI[label="Livello Intermedio"];
  SPA[label="Livello Avanzato"];
  START -> T -> TB;
  T -> TA;

  START -> S -> SP -> SPB;
  SP -> SPI;
  SP -> SPA;
}
....

// Definire le procedure per la codifica delle conoscenze che emergono nel corso delle interazioni tra i membri della CdP.:: __ANS__
// Creare una libreria di oggetti cognitivi utilizzando i documenti raccolti nella fase preliminare della progettazione.:: __ANS__
// Predisporre moduli e percorsi di autoformazione affinché i nuovi membri della comunità possano rapidamente allineare le proprie conoscenze con quelle degli altri utenti.:: __ANS__

=== Definizione della struttura organizzativa

Viene fornita di seguito la definizione della struttura organizzativa che consiste nell'individuale i ruoli, compiti e responsabilità che dovranno assumersi.

Soggetto promotore:: L'accademia musicale "`X`" è il soggetto promotore, la quale si è rivolta al team FSC per poter creare l'ambiente che la comunità di pratica andrà ad utilizzare. Ad essa spetta l'organizzazione dei momenti di socializzazione, la facilitazione delle attività e delle relazioni tra i membri della comunità e la promozione dell'immagine della stessa.
Essi comunicano con tutti i membri della comunità di pratica per cogliere tutti i bisogni che devono essere soddisfatti, in modo da essere sempre aggiornati e al passo con le nuove necessità sorgenti.

Community manager:: Personale di segreteria si occupa della creazione dei corsi e dell'assegnazione ai relativi docenti. È responsabile del funzionamento dell'ambiente per quanto riguarda, anche, la fruizione dei certificati agli studenti che hanno conseguito con successo i corsi al quale sono iscritti. 
Essi comunicano con i docenti per poter assegnarli ai corsi dei quali sono responsabili, per conoscere a quali studenti fare il certificato di superamento corso. Comunicano con gli studenti per poter consegnare questi certificati.

Content manager:: I docenti interni all'accademia provvedono alla generazione di contenuti, alla loro fruizione, alla selezione e diffusione di artefatti aggiuntivi utili ai membri della comunità e al loro imagazzinamento. Inoltre, sono i docenti a creare i test che gli allievi sono sottoposti mediante la piattaforma.
Essi comunicano con gli studenti per poter effettuare le lezioni, fornirgli gli strumenti necessari per lo studio, per poter effettuare delle video conferenze, test e così via.

Esperto:: Altri docenti (interni o esterni) o ospiti. Sono figure importanti soprattutto per arricchire il bagaglio musicale di ogni singolo studente. L'esperto è colui specializzato (certificato che non) in un determinato settore in grado di approfondire determinati argomenti. Sono figure che sono chiamate a presenziare per workshop, masterclass, e così via.
Essi comunicano si con i docenti del corso di riferimento per l'organizzazione delle masterclass, workshop e altro, e sia con gli studenti con i quali effettuare questi seminari e trasmettergli la loro conoscenza.

System Administrator:: Il team FSC si occupa delle questioni di carattere tecnico e della gestione della piattaforma tecnologica attraverlo la quale interagiscono i membri della comunità.
Il team comunica con l'accademia che ha richiesto la realizzazione della piattaforma per motivi tecnici e altro relativi alla stessa.

=== Avvio della comunità
Di seguito viene fornito l'avvio della comunità che consiste nella definizio di azioni e di strategie che dovranno essere messe in atto nel momento in cui la comunità prenderà vita.

Dimensionamento della comunità:: La comunità non ha limiti prestabiliti nella sua dimensione, tuttavia si lascia la libertà al docente di organizzare le proprie lezioni nei modi più consoni e con limiti di utenti a piacere (eventualmente dividendo tutti i participanti in più "`gruppi`", pur restando un unico corso).

Definizione di una guida per i partecipanti:: __Si fornisce il manuale utente del sistema, nonché delle note dei docenti all'interno del corso.__

Assegnazione dei ruoli chiave e formazione:: I docenti sono gli insegnanti già appartenenti all'accademia, e sono automaticamente iscritti (e aggiornati) dalla segreteria. Eventuali iscrizioni al sistema, sono da considerarsi "`studenti`".

Meeting iniziale e consolidamento del gruppo:: _Riunione del 25 aprile 2020 dalle 16:00?_

=== Gestione

[faq]
Come controllare l’adozione degli strumenti tecnologici più adatti alle esigenze di comunicazione e collaborazione online?:: Il gruppo di system administration ha la responsabilità di mantenere sempre aggiornato e sicuro il sistema.

Come anticipare e prevenire problemi tecnici legati all’uso della rete?:: V. risposta precedente.

Come curare l’accoglienza facendo in modo che i partecipanti si sentano i benvenuti?:: Durante le fasi di registrazione al sistema e ai corsi, si mostreranno messaggi di benvenuto/bentornato.

Come curare il processo di orientamento?:: Mediante una suddivisione in categorie visibile nella home page

Come sviluppare il senso di appartenenza alla comunità?:: _Attraverso forum, metodi di messaggistica e attraverso dirette condivise per sperimentare le conoscenze acquisite._ Gestione dei profili personali, (facilitazione delle comunicazioni), utilizzare meccanismi di personalizzazione della propria pagina personale, nidificare le aree di discussione (discussione corso, discussione gruppo).

Come fare in modo che ciascuno si senta coinvolto?:: _V. sopra_

Come prevenire eventuali situazioni critiche?:: Sistemi di FAQ, _Attraverso un sistema di gestione di segnalazioni alla segreteria_, pubblicazione di una guida passo-passo

Come alimentare e mantenere interessante l’interazione tra i membri della comunità?:: _Attraverso forum, messaggistica e videolezioni._ Chat, con possibiilità di caffè virtuali, sistemi di comunicazione broadcast, videoconferenza VoIP [sincrona], forum,

=== Monitoraggio e valutazione

[faq]
Quali indicatori prendere in esame? Il numero di messaggi scambiati? di documenti prodotti?:: Numero di post attivi e commenti sui form, numero di documenti prodotti, rapporto fra numero di iscritti ai corsi e iscritti alla piattaforma.

Qual è il grado di usabilità dell’ambiente online?:: Il sistema deve essere utilizzabile dalla maggior parte degli utenti. Deve, per quanto possibile e compatibile con la documentazione a disposizione dei docenti, essere garantito un alto grado di accessibilità delle risorse.

È utile sottoporre periodicamente agli utenti dei questionari di gradimento?:: Sì, al termine di "`periodi`" di insegnamento (per esempio, semestri) e al termine dei corsi stessi.

Quali scadenze dare all’attività di valutazione?:: La definizione delle scadenze delle attività di valutazione è lasciata al docente. In generale, si considera un tempo di 6 mesi dall'iscrizione.

== Dimensione tecnologica

_Analisi e scelta delle piattaforme._
