= Progettazione ambiente

== Fase preliminare

=== Analisi dei bisogni

Il committente è un'accademia musicale ("`X`"). Il sistema deve essere una
piattaforma di e-learning per tale accademia. L'accademia ("`X`") richiede una
strutturazione della piattaforma semplice, in modo tale da ridurne al minimo la
curva di apprendimento. È stato richiesto di avere un unico corso per singolo
strumento, nel quale sia possibile suddividere gli studenti in gruppi diversi
(per esempio, per età in modo da non rendere difficile la comunicazione tra
docenti e studenti).

L'accademia ha espresso la necessità di avere un ambiente per i propri studenti
che funda da supporto, sostegno e anche di rimpiazzo ai suoi corsi tenuti nella
struttura della scuola. I bisogni evidenziati sono vari, tra cui:

* L'organizzazione sente la necessità di far proseguire le lezioni (e gli
  studenti sentono la necessità di continuare a usufruirne) in un periodo di
  emergenza internazionale, in modo da ridurre i rischi di contagio (rispettando
  le ordinanze attuali) e da limitare l'impatto sul piano economico.
* Si vuole permettere agli studenti lavoratori (o in altro modo impossibilitati
  alla frequenza fisica dei corsi) di coltivare le proprie passioni e migliorare
  costantemente le proprie abilità.
* Si vuole permettere di adattare il processo di apprendimento alle proprie
  caratteristiche e modalità di apprendimento.
* Si vuole permettere di approfondire argomenti che non sono stati trattati
  durante le lezioni frontali riguardanti, ad esempio, la teoria musicale.
* Si vuole favorire un'erogazione rapida dei contenuti didattici in modo rapido,
  raggiungendo tutti i partecipanti di un ipotetico corso con una sola azione.

Il sistema va quindi inserito all'interno del contesto di un'accademia musicale
e deve supportare gli studenti in modo da poterli arricchire con qualsiasi mezzo
comunicativo. In tale contesto, tutti gli studenti sono pienamente consepevoli
del percorso di studi intrapreso e della quantità di tempo e impegno necessaria
a completarlo. Inoltre, deve essere garantita un buon grado di ufficialità del
percorso di studi, rilasciando certificati.

L'obiettivo principale che la piattaforma si propone di conseguire è, quindi,
quello di fornire agli studenti la possibilità di studiare a prescindere dalla
disponibilità temporale e dalla locazione geografica. Gli obiettivi specifi sono
poi vari in base allo specifico corso. 

I corsi possono essere divisi in due macrocategorie: teorici (teoria musicale) e
pratici (imparare uno strumento musicale).

Gli obiettivi principali per un corso teorico riguardano:

* L'erogazione dei contenuti legati all'aspetto teorico musicale.
* L'apprendimento dei concetti base e fondamentali per il coseguimento di
  qualsiasi altro percorso pratico e/o teorico.
* L'apprendimento dei concetti di teoria avanzata.
* L'approfondimento di argomenti aggiuntivi per lo studente che ritiene egli
  stesso interessante e stimolante per la sua conoscenza.
* Il ripasso di argomenti che con il tempo lo studente che ritiene di non
  ricordare alla perfezione, per esempio dimenticando la terminologia, un
  concetto base, come eseguire un esercizio eccetera (oppure può essere lo
  stesso docente a indicare allo studente quali argomenti è necessario che
  ripassi).

Gli obiettivi principali per un corso pratico, invece, riguardano:

* L'insegnamento di tecniche basilari per il primo approccio allo strumento
  scelto da parte dell'allievo.
* L'insegnamento di tecniche specifiche di esecuzione di un determinato
  virtuosismo (ad esempio il _tapping_, una tecnica per la chitarra).
* L'erogazione di contenuti (che possono essere documenti testuali, video,
  oppure spartiti) riguardanti le tecniche e/o l'esecuzione dei brani che il
  docente vuole insegnare ai suoi studenti. In questo modo il docente potrà
  mostrare ai suoi studenti tutte le varie caratteristiche del brano proposto.

=== Caratterizzazione della comunità

Il sistema commissionato è una piattaforma di e-learning in cui l'accademia può
spostare la propria didattica: la comunità su cui si basa è la stessa comunità
che partecipa alla didattica in sede. La comunità può, quindi, essere divisa in
due gruppi: gli "`allievi`" (coloro che usufruiscono della didattica) e i
"`maestri`". In questi due macrogruppi è, inoltre, possibile individuare alcuni
sottogruppi: gli allievi possono essere suddivisi per competenze e fasce di età;
i maestri possono essere divisi per aree di competenza. In generale, i membri
della comunità sono tutti accumunati dal proprio dominio di conoscenza: la
musica. In tale campo, tutti i membri sono interessati (in varia misura) a
migliorare le proprie conoscenze e abilità. Problematiche comuni da affrontare
con una comunità di questo tipo sono riguardanti la padronanza di linguaggio
(sia tecnico che non: si pensi alla differenza nella capacità di esprimersi e
comprendere che si ha tra un bambino e un adulto) e la differenza nei tempi da
dedicare all'apprendimento.

Il campo musicale e, più in piccolo, le conoscenze e competenze che l'accademia
ha l'obiettivo di fornire ai propri allievi sono oggetti ben codificati: è
possibile strutturare l'intera conoscenza in tale ambito con una struttura ad
albero (riportato in <<img-dominio-conoscenza>>).

Non è prevista un'area geografica in cui circoscrivere le provenienze dei membri
della comunità ma, data la natura tendenzialmente circoscritta (nelle sue fasi
primordiali) di un'accademia musicale, si presuppone che tutti i membri della
comunità parlino la lingua italiana, lingua in cui saranno erogati i corsi.
Questo ambiente permette, anzi, di avere studenti e docenti collocati in luoghi
differenti in modo da congiungere passione, studio e voglia di imparare
argomenti nuovi. Ciò risulta essere una risorsa fondamentale per l'accademia, in
quanto è possibile avere contatti con esperti musicali normalmente
impossibilitati a recarsi nella struttura della stessa accademia dando loro la
possibilità di fornire il proprio contributo per l'esperienza e bagaglio
culturale degli allievi.

Non è possibile prevedere delle capacità informatiche della comunità, data la
diversità di età e percorsi seguiti, tuttavia si pressupone che tutti i membri
abbiano una competenza di base nell'utilizzo di un browser internet.

Attualmente, in sede, si possono tenere lezioni sia di gruppo che individuali ed
è possibile collaborare incontrandosi. Inoltre, gli allievi sono liberi di
contattarsi a piacere con varie metodologie. Le lezioni sono tutte in sede e le
comunicazioni possono avvenire sia online che non. Più in dettaglio, le
comunicazioni online sono principalmente sincrone (mediante _chat_ utilizzando
sistemi come WhatsApp, Telegram, Facebook, etc), ma possono anche essere
asincrone. La piattaforma deve quindi dare la possibilità a tutti i suoi membri
di comunicare, utilizzando forum, comunicazioni in broadcast, chat (con
eventuali caffè virtuali). Tali comunicazioni possono riguardare, per esempio,
notifiche varie da parte dei docenti, organizzazione di saggi, confronto fra gli
alunni etc. Deve inoltre essere possibile gestire video conferenze, per favorire
l'attività didattica.

== Dimensione gestionale

=== Flussi di comunicazione

L'interazione fra studenti e docenti può, attualmente, avvenire mediante scambi
verbali e condivisione di documenti. Per questo motivo, la piattaforma deve
fornire la possibilità di gestire entrambe le forme di comunicazione. In
particolare, per gli scambi verbali devono essere disponibili forum, chat, video
conferenze, etc. Per quanto riguarda lo scambio di documenti, deve essere
possibile per i docenti fornire del materiale ai propri studenti e, per
quest'ultimi, usufruirne e condividerne di nuovo. Le metodologie specifiche
circa l'erogazione dei contenuti e sulle modalità di comunicazione sono quindi
varie e saranno i docenti e i loro studenti a decidere quali adottare e
utilizzare.

La comunità è interamente gestita dalla segreteria dell'accademia, per cui i
suoi membri non devono prendere decisioni. Più nel dettaglio, ai docenti saranno
attribuiti i corsi d'ufficio (quindi è previsto un solo corso per ogni tipologia
di argomento) e gli studenti seguiranno il percorso didattico del corso a cui si
iscrivono. Quindi, riassumento, le uniche decisioni che i membri devono prendere
riguardano i corsi a cui iscriversi (per gli studenti), la definizione del
percorso didattico (per i docenti) e eventuali decisioni che i docenti decidono
di lasciare agli studenti (che non è possibile prevedere a priori).

Data l'alta strutturazione delle conoscenze del dominio musicale (si veda
<<img-dominio-conoscenza>>), il modo migliore per alimentare la base di
conoscenza della comunità è quello di organizzare e classificare le discussioni
e il materiale in base all'argomento trattato, lasciando la possibilità allo
studente di scegliere il livello di dettaglio a cui arrivare, per poi lasciare
al docente l'onere di valutare se lo studente ha raggiunto il suo obiettivo
(ovverosia il livello precedentemente prefissato mediante la scelta del corso).

=== Definizione della conoscenza comunitaria

[#img-dominio-conoscenza]
.Mappa concettuale dominio di conoscenza. Con "`Strumento`" si intende un qualsiasi strumento musicale (per esempio, chitarra o pianoforte): la stessa struttura riportata è presente a prescindere dallo specifico strumento preso in esame.
[blockdiag, mappa-dominio-conoscenza, svg] 
....
blockdiag {
  START[label="La Musica"];
  T[label="Teoria"];
  S[label="Pratica"];
  TB[label="Teoria Base"];
  TA[label="Teoria Avanzata"];
  SP[label="Strumento"];
  SPB[label="Livello Base"];
  SPI[label="Livello Intermedio"];
  SPA[label="Livello Avanzato"];
  START -> T -> TB;
  T -> TA;

  START -> S -> SP -> SPB;
  SP -> SPI;
  SP -> SPA;
}
....

=== Definizione della struttura organizzativa

Viene fornita di seguito la definizione della struttura organizzativa, in cui si
identificano i ruoli, associati ai compiti e alle reponsabilità che dovranno
assumersi.

Soggetto promotore:: L'accademia musicale è il soggetto promotore, la quale si è
rivolta al team FSC per poter creare l'ambiente che la comunità di pratica andrà
a utilizzare. A essa spetta l'organizzazione dei momenti di socializzazione, la
facilitazione delle attività e delle relazioni tra i membri della comunità e la
promozione dell'immagine della piattaforma. Essi comunicano con tutti i membri
della comunità di pratica per cogliere tutti i bisogni che devono essere
soddisfatti, in modo da essere sempre aggiornati e al passo con le nuove
necessità sorgenti.

Community manager:: Il personale di segreteria si occuperà della creazione dei
corsi e della loro assegnazione ai relativi docenti. È anche responsabile del
funzionamento dell'ambiente per quanto riguarda il rilascio dei certificati agli
studenti che hanno completato con successo i corsi ai quali sono iscritti. 

Content manager:: I docenti interni all'accademia provvedono alla generazione di
contenuti, alla verifica della loro fruibilità, alla selezione e diffusione di
materiali aggiuntivi utili ai membri della comunità e al loro immagazzinamento.
Inoltre, sono i docenti a creare i test che gli allievi sono sottoposti mediante
la piattaforma. Essi comunicano con gli studenti per poter effettuare le
lezioni, fornirgli gli strumenti necessari per lo studio, per poter effettuare
delle video conferenze, dei test e così via.

Esperto:: Altri docenti (interni o esterni) o ospiti sono figure importanti
soprattutto per arricchire il bagaglio musicale di ogni singolo studente.
L'esperto è colui specializzato in un determinato settore in grado di
approfondire determinati argomenti. Sono figure che sono chiamate a presenziare
per workshop, masterclass, e così via. Essi comunicano sia con i docenti del
corso di riferimento per l'organizzazione, sia con gli studenti con i quali
effettuare questi seminari e trasmettere loro conoscenza. Eventuali inviti, sono
gestiti dalla segreteria dell'accademia, sotto richiesta dei docenti.

System Administrator:: Il team FSC si occupa delle questioni di carattere
tecnico e della gestione della piattaforma tecnologica attraverso cui
interagiscono i membri della comunità. Il team ha il compito di comunicare con
l'accademia che ha richiesto la realizzazione della piattaforma per motivi
tecnici e gestionali.

=== Avvio della comunità

In riferimento alla comunità della piattaforma, non vi sono limiti prestabiliti
nella sua dimensione. Tuttavia, per garantire la qualità di insegnamento
migliore, i docenti sono liberi di organizzare i propri corsi e le proprie
lezioni nei modi più consoni, per esempio riducendo il numero di partecipanti in
contemporanea suddividendo il corso in "`gruppi`".

Per garantire una fruizione senza attrito della piattaforma, il team si impegna
a fornire dei manuali utente sia ai docenti che agli studenti, in modo da
permettere di imparare da subito le basi del funzionamento della piattaforma.

La comunità è basata sulla platea attualmente esistente: i docenti sono gli
insegnanti già appartenenti all'academia (la loro iscrizione e gestione è
lasciata alla segreteria). Inoltre, tutti gli attuali studenti dell'academia
faranno automaticamente parte della nuova comunità, che può estendersi mediante
nuove iscrizioni (che avvengono come "`studenti`").

=== Gestione

Al fine di controllare l'adozione degli strumenti tecnolofici più adatti alla
comunicazione e alla collaborazione online, il team FSC si impegna a effettuare
le scelte migliori e a mantenere sempre aggiornato l'ambiente di lavoro della
piattaforma. In questo modo, saranno anche ridotti al minimo il rischio di
problemi tecnici legati all'uso della rete, che saranno comunque gestiti dal
team di _system administration_.

Per rendere il sistema il più accogliente possibile, in modo da far sentire i
nuovi partecipanti i benvenuti, si mostreranno messaggi di benvenuto sia durante
la registrazione al sistema che durante la registrazione ai corsi (eventualmente
anche con messaggi via mail). Per mantenere alto questo senso di accoglienza e
permettere agli utenti di orientarsi il più facilmente possibile nel sistema, si
mostreranno i corsi e la loro suddivisione in categorie sin dalla home page
della piattaforma, oltre ad utilizzare titoli e paragrafi che permettano sempre
all'utente di individuare la pagina in cui si trova.

Affinché gli utenti si sentano effettivamente parte della comunità, saranno
messi a disposizione forum e metodi di messaggistica (chat e caffè virtuali).
Inoltre, sarà data la possibilità agli utenti di personalizzare la propria
pagina personale e i propri profili e le aree di comunicazione saranno
nidificate, al fine di far sentire gli utenti parte di un gruppo ristretto e
sentirsi sempre coinvolti. Inoltre, queste strategie, unitamente ai sistemi di
comunicazione in broadcast e alle videoconferenze VoIP (sincrone), consentono di
mantenere sempre viva e interessante l'interazione fra i membri della comunità.

Eventuali situazioni critiche (di tipo tecnico, personale o di gruppo) saranno
gestite mediante sistemi di FAQ (__Frequently Asked Questions__) e la
pubblicazione di una guida passo-passo (di cui si è già parlato nella
<<_avvio_della_comunità>>). Eventuali problematiche e criticità non risolte
utilizzando le precedenti tecniche, saranno gestite mediante un sistema di invio
di segnalazioni alla segreteria.

=== Monitoraggio e valutazione

Per monitorare e valutare la qualità della vita della comunità possono essere
presi in esame diversi fattori, fra cui il numero di post attivi e di commenti
sui forum, il numero di documenti prodotti e il rapporto fra il numero di
iscritti ai corsi e il numero di studenti che portano a compimento gli studi.
Inoltre, è possibile sottoporre questionari di gradimento agli studenti per
valutare la qualità degli insegnamenti (per esempio, al termine degli stessi).

Il sistema deve garantire un alto grado di usabilità, in modo da essere
facilmente utilizzabile dalla maggior parte degli utenti. Inoltre, per quanto
possibile e compatibilmente alla documentazione a disposizione dei docenti, deve
essere garantito un alto grado di accessibilità delle risorse al fine di
includere anche studenti con diverse tipologie di disabilità.

Infine, per quanto concerne l'attività didattica, non è possibile prevedere a
priori delle scadenze per le attività di valutazione. Tali definizioni sono
lasciate in primis alla segreteria e in secundis ai docenti (anche se in
generale si può assumere un tempo di circa 6 mesi dall'iscrizione dello
studente). La scelta delle metodologie di valutazione sono, poi, lasciate ai
docenti. 

== Dimensione tecnologica

_Analisi e scelta delle piattaforme._
