= Progettazione ambiente

== Fase preliminare

=== Analisi dei bisogni

Il committente è un'accademia musicale ("`X`"). Il sistema deve essere una piattaforma di e-learning per tale accademia.
L'accademia ("`X`") richiede una strutturazione della piattaforma semplice, in modo tale da ridurre al minimo l'apprendimento dell'ambiente che si vuole creare. È stato richiesto di avere un unico corso per singolo strumento, nel quale è possibile poi aggiungere gruppi diversi che riguardano comunque sia lo stesso strumento. Per questo una necessità potrebbe essere che ci sia la suddivisione per età tra gli studenti in modo da non rendere difficile l'apprendimento. 

L'accademia ha espresso la necessità di creare un ambiente per i suoi studenti che fosse di supporto, sostegno e anche di sostituzione (nel caso in cui ci posso essere delle epidemie e pandemie, come la situazione attuale) ai suoi corsi tenutosi nella struttura della scuola. I bisogni evidenziati sono vari:
* L'organizzazione sente la necessità di far proseguire le lezioni (e gli studenti sentono la necessità di usufruirne) in un periodo di emergenza internazionale, in modo da limitare l'impatto sul piano economico e impedire gravi situazioni di contagio. 
* Si vuole permettere agli studenti lavoratori (o in altro modo impossibilitati alla frequenza fisica dei corsi) di coltivare le proprie passioni e migliorare costantemente le proprie abilità.
* Si vuole permettere di adattare il processo di apprendimento alle proprie caratteristiche e modalità di apprendimento.
* Si vuole permettere di approfondire argomenti che non sono stati trattati durante le lezioni frontali riguardanti, ad esempio, la teoria musicale.
* Attraverso questo ambiente, si vuole permettere di erogare contenuti didattici in modo rapido, raggiungendo tutti i partecipanti di un ipotetico corso con una sola azione.

 Il contesto è, appunto, quello di un'accademia musicale che vuole sostenere e supportare i suoi studenti in modo da poterli arricchire con qualsiasi mezzo comunicativo a disposizione. 
 Ovviamente, tutti gli studenti sono consapevoli del percorso di studi intrapreso e della quantità di impegno necessaria. Inoltre, deve essere garantita un'ufficialità del percorso di studi.

Gli obiettivi principali che la comunità si propone di conseguire riguardano: la possibilità di studiare a prescindere dalla disponibilità temporale e dalla locazione geografica. Gli obiettivi precisi sono poi vari in base allo specifico corso. I corsi possono però essere divisi in due macrocategorie: teorici (teoria musicale) e pratici (imparare uno strumento musicale).
Gli obiettivi principali per un corso teorico riguardano:
* L'erogazione dei contenuti legati all'aspetto teorico musicale.
* L'apprendimento dei concetti base e fondamentali per il coseguimento di qualsiasi altro percorso pratico e/o teorico.
* L'apprendimento dei concetti di teoria avanzata.
* L'approfondimento di argomenti aggiuntivi per lo studente che ritiene egli stesso interessante e stimolante per la sua conoscenza.
* Il ripasso di argomenti che con il tempo lo studente che ritiene di non ricordare alla perfezione dimenticando, ad esempio, la terminologia, un concetto base, come eseguire un esercizio eccetera (oppure può essere lo stesso docente a indicare allo studente quali argomenti è necessario che ripassi).

Gli obiettivi principali per un corso pratico, invece, riguardano:
* L'insegnamento di tecniche basilari per il primo approccio allo strumento da parte dell'allivo.
* L'insegnamento di tecniche specifiche di esecuzione di un determinato virtuosismo (ad esempio il _tapping_ è una tecnica per la chitarra).
* L'erogazione di contenuti (che possono essere descrizioni testuali video, oppure spartiti) riguardanti le tecniche e/o l'esecuzione dei brani che il docente vuole insegnare ai suoi studenti. In questo modo il docente potrà mostrare ai suoi studenti tutte le varie caratteristiche del brano proposto.

=== Caratterizzazione della comunità

La piattaforma ("`X`"), basata sul LMS "`Moodle`", è stata creata dal team FSC come richiesto dalla accademia musicale ("`X`") per supportare i suoi studenti e suoi docenti per favorire la comunicazione (anche in orari differenti da quelli di lezione), per l'erogazione semplice dei contenuti (sia quelli affrontanti che non), gli studenti che per motivi di impegni e/o lavoro non possono presenziare, oppure affrontare pandemie ed epidemie (come quella che si è costretti ad affrontare oggi) e altri motivi esplicitati nella sezione "`Analisi dei bisogni`" (si veda sopra). 

La comunità di pratica, al quale si fa riferimento in questo contesto, è divisibile in due categoria: "`Allievi`" e "`Maestri`".
Gli allievi sono a loro volta suddivisi per livello di competenze in ambito musicale (_base_, _intermedio_, _avanzato_).
Anche i maestri possono essere suddivisi ulteriormente in sotto categorie, ad esempio maestri che insegnano ai bambini e maestri che insegnano agli adulti.
Proprio per questo, si è voluto creare un unico corso, ad esempio, riguardante ad uno specifico strumento, il quale al suo interno conterrà gruppi differenti. Ad esempio, sarà presente un gruppo per i bambini che suonano la chitarra e un gruppo di adulti che suonano lo stesso strumento ma entrambi fanno parte dello stesso corso ovvero, restando nell'esempio, il corso di chitarra.

Geograficamente la CdP non ha un centro ben preciso al di fuori della struttura in cui l'accademia è situata, ma si suppone che i membri della CdP siano italiani (o conoscano la lingua italiana) data la realtà tendenzialmente ben circoscritta di un'accademia musicale.
Questo ambiente permette, inoltre, di avere studenti e docenti collocati in luoghi differenti in modo da congiungere passione, studio e voglia di imparare argomenti nuovi. Risulta essere una risorsa fondamentale per l'accademia, in quanto può avere contatto con grandi esperti musicali che sono impossibilitati nel recarsi nella struttura della stessa accademia ma che può dare il suo contributo fondamentale per l'esperienza e bagaglio musicale degli allievi.

Le competenze informatiche sono miste, ma è logico supporre una minima competenza basilare nell'uso di un browser internet.

Il dominio di conoscenza è la musica. I membri della CdP sono tutti, in varia misura, interessati a migliorare le proprie conoscenze in tale campo. Problematiche comuni riguardano la padronanza del linguaggio (sia tecnico che non, si pensi a dei bambini), il tempo che si può dedicare all'apprendimento. __Non vi sono manuali e procedure codificate, se non quelle dettate dalla teoria musicale.__

Attualmente, si possono tenere lezioni di gruppo o individuali in una struttura ed è possibile collaborare incontrandosi. Inoltre, gli allievi sono attualmente liberi di contattarsi a piacere con varie metodologie. Attualmente le lezioni sono in presenza, le comunicazioni sono sia online che non. Le comunicazioni online sono sia sincrone che asincrone, ma principalmente sincrone (Whatsapp, Telegram, Facebook, etc).
Con l'utilizzo della piattaforma che si è creata si vuole dare la possibilità ai docenti e agli studenti di creare forum con degli obiettivi specifici (come possono essere le comunicazioni del docente, l'organizzazione di un saggio, il confronto tra gli stessi alunni, e via dicendo). Si vuole dare la possibilità di creare delle video conferenze, in modo da aggirare l'ostacolo di pandemie ed epidemie, andando avanti con le lezioni in modo continuo e diretto.

== Dimensione gestionale

=== Flussi di comunicazione
L'interazione tra gli studenti e i docenti dell'accademia musicale ("`X`") può avvenire sia attraverso scambi verbali (come ad esempio l'utilizzo di forum, la creazione di video conferenze,...) e sia attraverso la condivisioni di documenti. Si prenda il caso di un docente di questa accademia: può inserire documenti riguardati la lezione, può inserire glossari in modo da specificare e dettagliare la terminologia che si utilizza, e via dicendo.
Le possibilità offerte di erogazione di contenuti e di comunicazione sono varie, ovviamente saranno docenti e studenti che decideranno quali strumenti adottare per le loro necessità.

I membri della comunità di pratica non devono prendere decisioni se non riguardanti i corsi da intraprendere. Devono, inoltre, poter fissare appuntamenti con i docenti (es: lezioni aggiuntive, richieste di chiarimenti, approndimenti, etc). Devono poter esprimere preferenze e proposte dai docenti, se questi lo ritengono utile.

Il modo migliore per alimentare la base di conoscenza della CdP in questo ambito è quello di organizzare e classificare le discussioni in base a un argomento, lasciando la possibilità allo studente di scegliere il livello a cui arrivare per poi far valutare al docente se lo studente ha raggiunto il suo obiettivo (ovvero il livello prefissato).

=== Definizione della conoscenza comunitaria

[faq]
Elaborare una mappa concettuale del dominio di conoscenza della CdP in modo tale da specificare argomenti, categorie e sottocategorie utili alla classificazione e all’organizzazione dei documenti nei quali saranno formalizzate le conoscenze della comunità.:: __ANS__

Definire le procedure per la codifica delle conoscenze che emergono nel corso delle interazioni tra i membri della CdP.:: __ANS__

Creare una libreria di oggetti cognitivi utilizzando i documenti raccolti nella fase preliminare della progettazione.:: __ANS__

Predisporre moduli e percorsi di autoformazione affinché i nuovi membri della comunità possano rapidamente allineare le proprie conoscenze con quelle degli altri utenti.:: __ANS__

=== Definizione della struttura organizzativa

Viene fornita di seguito la definizione della struttura organizzativa che consiste nell'individuale i ruoli, compiti e responsabilità che dovranno assumersi.

Soggetto promotore:: L'accademia musicale "`X`" è il soggetto promotore, la quale si è rivolta al team FSC per poter creare l'ambiente che la comunità di pratica andrà ad utilizzare. Ad essa spetta l'organizzazione dei momenti di socializzazione, la facilitazione delle attività e delle relazioni tra i membri della comunità e la promozione dell'immagine della stessa.
Essi comunicano con tutti i membri della comunità di pratica per cogliere tutti i bisogni che devono essere soddisfatti, in modo da essere sempre aggiornati e al passo con le nuove necessità sorgenti.

Community manager:: Personale di segreteria si occupa della creazione dei corsi e dell'assegnazione ai relativi docenti. È responsabile del funzionamento dell'ambiente per quanto riguarda, anche, la fruizione dei certificati agli studenti che hanno conseguito con successo i corsi al quale sono iscritti. 
Essi comunicano con i docenti per poter assegnarli ai corsi dei quali sono responsabili, per conoscere a quali studenti fare il certificato di superamento corso. Comunicano con gli studenti per poter consegnare questi certificati.

Content manager:: I docenti interni all'accademia provvedono alla generazione di contenuti, alla loro fruizione, alla selezione e diffusione di artefatti aggiuntivi utili ai membri della comunità e al loro imagazzinamento. Inoltre, sono i docenti a creare i test che gli allievi sono sottoposti mediante la piattaforma.
Essi comunicano con gli studenti per poter effettuare le lezioni, fornirgli gli strumenti necessari per lo studio, per poter effettuare delle video conferenze, test e così via.

Esperto:: Altri docenti (interni o esterni) o ospiti. Sono figure importanti soprattutto per arricchire il bagaglio musicale di ogni singolo studente. L'esperto è colui specializzato (certificato che non) in un determinato settore in grado di approfondire determinati argomenti. Sono figure che sono chiamate a presenziare per workshop, masterclass, e così via.
Essi comunicano si con i docenti del corso di riferimento per l'organizzazione delle masterclass, workshop e altro, e sia con gli studenti con i quali effettuare questi seminari e trasmettergli la loro conoscenza.

System Administrator:: Il team FSC si occupa delle questioni di carattere tecnico e della gestione della piattaforma tecnologica attraverlo la quale interagiscono i membri della comunità.
Il team comunica con l'accademia che ha richiesto la realizzazione della piattaforma per motivi tecnici e altro relativi alla stessa.

=== Avvio della comunità

Dimensionamento della comunità:: La comunità non ha limiti prestabiliti nella sua dimensione, tuttavia si lascia la libertà al docente di organizzare le proprie lezioni nei modi più consoni e con limiti di utenti a piacere (eventualmente dividendo tutti i participanti in più "`gruppi`", pur restando un unico corso).

Definizione di una guida per i partecipanti:: __Si fornisce il manuale utente del sistema, nonché delle note dei docenti all'interno del corso.__

Assegnazione dei ruoli chiave e formazione:: I docenti sono gli insegnanti già appartenenti all'accademia, e sono automaticamente iscritti (e aggiornati) dalla segreteria. Eventuali iscrizioni al sistema, sono da considerarsi "`studenti`".

Meeting iniziale e consolidamento del gruppo:: _Riunione del 25 aprile 2020 dalle 16:00?_

=== Gestione

[faq]
Come controllare l’adozione degli strumenti tecnologici più adatti alle esigenze di comunicazione e collaborazione online?:: Il gruppo di system administration ha la responsabilità di mantenere sempre aggiornato e sicuro il sistema.

Come anticipare e prevenire problemi tecnici legati all’uso della rete?:: V. risposta precedente.

Come curare l’accoglienza facendo in modo che i partecipanti si sentano i benvenuti?:: Durante le fasi di registrazione al sistema e ai corsi, si mostreranno messaggi di benvenuto/bentornato.

Come curare il processo di orientamento?:: _ANS?_

Come sviluppare il senso di appartenenza alla comunità?:: _Attraverso forum, metodi di messaggistica e attraverso dirette condivise per sperimentare le conoscenze acquisite._

Come fare in modo che ciascuno si senta coinvolto?:: _V. sopra_

Come prevenire eventuali situazioni critiche?:: _Attraverso un sistema di gestione di segnalazioni alla segreteria._

Come alimentare e mantenere interessante l’interazione tra i membri della comunità?:: _Attraverso forum, messaggistica e videolezioni._

=== Monitoraggio e valutazione

[faq]
Quali indicatori prendere in esame? Il numero di messaggi scambiati? di documenti prodotti?:: Numero di post attivi e commenti sui form, numero di documenti prodotti, rapporto fra numero di iscritti ai corsi e iscritti alla piattaforma.

Qual è il grado di usabilità dell’ambiente online?:: Il sistema deve essere utilizzabile dalla maggior parte degli utenti. Deve, per quanto possibile e compatibile con la documentazione a disposizione dei docenti, essere garantito un alto grado di accessibilità delle risorse.

È utile sottoporre periodicamente agli utenti dei questionari di gradimento?:: Sì, al termine di "`periodi`" di insegnamento (per esempio, semestri) e al termine dei corsi stessi.

Quali scadenze dare all’attività di valutazione?:: La definizione delle scadenze delle attività di valutazione è lasciata al docente. In generale, si considera un tempo di 6 mesi dall'iscrizione.

== Dimensione tecnologica

_Analisi e scelta delle piattaforme._
